### ISSUE TITLE
No lan option

### ISSUE THREAD

**Issue by Souloutkast** [LunaPixelStudios/Prominence#1]
### Describe the Bug

No option to open to lan in menu when in game 

### Reproduction Steps

1.start world 
2.hit ESC
3. No lan 
...

### Operating System

Windows 10 64bit

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence [FABRIC]

### Optifine

No

**Comment by chorbintime** [comment]
LAN does not work. You need to host a server using the serverpack or buy a server from Bisect.
