### ISSUE TITLE
No Lan?

### ISSUE THREAD

**Issue by Strawbulb** [LunaPixelStudios/Prominence#101]
### Describe the Bug

I am trying to play this with a friend, but I can't open to lan

### Reproduction Steps

1.
2.
3.
...

### Operating System

Mac

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Prominence II [FORGE]-v0.4.0.zip

### Optifine

No

**Comment by nvb-uy** [comment]
Unsupported
