### ISSUE TITLE
Items in inventory showing up

### ISSUE THREAD

**Issue by Randomperson406** [LunaPixelStudios/Prominence#102]
### Describe the Bug

Whenever I place something in my inventory it still shows up on my screen even after I close it.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-07-17_16 40 15](https://github.com/LunaPixelStudios/Prominence/assets/98376031/3c4a74c4-7b1f-4430-bb74-a1a9f04bde87)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.20

### Optifine

I used Optifine

**Comment by austeez** [comment]
Is there any way to fix this?

**Comment by EstrodimusS1** [comment]
just press "i" and it disappears

**Comment by austeez** [comment]
> just press "i" and it disappears

Thanks
