### ISSUE TITLE
Building Gadgets Crash

### ISSUE THREAD

**Issue by cauvacg** [LunaPixelStudios/Prominence#104]
### Describe the Bug

Everytime I go to the Building Gadgets's creative tab or digit "@Build" in the JEI my Minecraft crash

### Reproduction Steps

1.Open/Create a world
2.Go to "Building Gadgets" creative tab or search "@Build" on JEI
3.Minecraft Crash

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.0.3hf

### Optifine

No

**Comment by Teraphina** [comment]
if you add
buildinggadgets:construction_block

into the blacklist.cfg file in JEI config folder it will stop the crashing. it is the construction block for some reason is crashing the game when viewed in jei

**Comment by nvb-uy** [comment]
Does it also crash when in the inventory or is it solely a jei incompatibility?

**Comment by Teraphina** [comment]
dont know how to get it into my inventory without bringing it up in JEI crafting the powder and placing in water makes dense blocks and breaking those gives paste. made a vanilla pack with only jei and building gadgets and jei doesnt have a recipie for the blocks only the powder

**Comment by nvb-uy** [comment]
Enviado desde Proton Mail móvil

-------- Mensaje original --------

**Comment by Teraphina** [comment]
your responce does not have the "edited" parts of my last post... here they are...

Was able to use silk touch on the dense but that is not the items causing the issue

remembered about the give command. crashes as soon as you run the give command did not even see it populate in my inventory

**Comment by nvb-uy** [comment]
Fixed in latest version
