### ISSUE TITLE
Jukebox/Discs

### ISSUE THREAD

**Issue by Hisoyen** [LunaPixelStudios/Prominence#105]
### Describe the Bug

After placing a Jukebox, I've been trying to use the discs but they've just all been disappearing and it shows that the Jukebox is empty.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v0.5.0

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
Send latest log, Optifine is not supported
