### ISSUE TITLE
issues with binding and resetting certain keybinds

### ISSUE THREAD

**Issue by oLurz** [LunaPixelStudios/Prominence#107]
### Describe the Bug

sprint and crouch keybinds dont work even if i keep them default they still dont work

### Reproduction Steps

1. got to settings
2. go to rebind sprint or crouch
3. it automatically rebinds shift or ctrl with the key i pressed and it doesnt let me reset the bind also the binds dont work at all
4.
...

### Screenshots and Videos

![image_2023-07-18_231339798](https://github.com/LunaPixelStudios/Prominence/assets/72787088/bc2cbdc6-9aaa-4444-a499-4d4239978b47)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence 2 fabric

### Optifine

No

**Comment by nvb-uy** [comment]
Can't repro
