### ISSUE TITLE
AE2 guide crashing client due to starlight incompatability

### ISSUE THREAD

**Issue by 100lewi** [LunaPixelStudios/Prominence#109]
### Describe the Bug

If you try to open the guide for ae2 the client crashes due to incompatability with starlight.

recommended action:
Remove Starlight from the client side of prominence 2 [fabric] as even the devs of the mod say it's obsolete on the client side.

"Minecraft 1.20 Light engine changes
Please see: https://gist.github.com/Spottedleaf/6cc1acdd03a9b7ac34699bf5e8f1b85c TL;DR Mojang improved upon their own light engine using the same performance critical designs from Starlight. As a result, they have closed the performance gap, obsoleting Starlight on the client side." - Starlight Curseforge page (https://www.curseforge.com/minecraft/mc-mods/starlight)

### Reproduction Steps

1. Hold [W] while hovering over any ae2 item to attempt to open the guide.

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence 2 [Fabric] v0.5

### Optifine

No

**Comment by nvb-uy** [comment]
Thanks, will be removed soon
