### ISSUE TITLE
Start scripts for server requires certain resources to be available

### ISSUE THREAD

**Issue by smsteel** [LunaPixelStudios/Prominence#11]
### Describe the Bug

`start.ps1` or `start.sh` requires: `https://meta.fabricmc.net/v2/versions/loader/` and such for it to be able to work. 

Is it possible to check if you've got the required files to skip http requests?

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.5

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
fixed in 1.6.1 server pack
