### ISSUE TITLE
Container without loot table

### ISSUE THREAD

**Issue by Rebell64** [LunaPixelStudios/Prominence#110]
### Describe the Bug

"The loot table for this container [luna_structures:chests/taiga_inn/taiga_inn_barrels] resolved to empty and loot could not be generated. Check your `latest.log` for errors.", this is what i get when i try to open the barrels in the small room under the stairs to the left of the main entrance of the house in the screenshot. And im running 1.20.1, but can't select it in the forum.

### Reproduction Steps

1. go to the house in the screenshot
2. find the room beneath the main entrance
3. open the barrels

### Screenshots and Videos

![2023-07-22_16 32 42](https://github.com/LunaPixelStudios/Prominence/assets/67365702/bc21633e-c1cb-412e-933b-fb8552716539)

### Operating System

Fedora Linux 38 (Workstation Edition) x86_64 @ Kernel: 6.3.12-200.fc38.x86_64

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v0.5.0

### Optifine

No

**Comment by Rebell64** [comment]
the bot is wrong, im using fabric

**Comment by nvb-uy** [comment]
Fixed in v2.0.0
