### ISSUE TITLE
owo > handshake failure 

### ISSUE THREAD

**Issue by Evinh0** [LunaPixelStudios/Prominence#111]
### Describe the Bug

this bug only occurs when i try to join an online server, It will not let me join the server becasue it says: owo > handhshake failure incompatible cliant, i do not know what to do and I can't play online becasue of this 

### Reproduction Steps

1. I 
2. Don't 
3. Know 
...

### Screenshots and Videos

![Screenshot 2023-07-22 153323](https://github.com/LunaPixelStudios/Prominence/assets/140279168/7b660d48-5a80-4396-9e7a-00e75e198e41)

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

prominence fabric 

### Optifine

No

**Comment by nvb-uy** [comment]
Likely a mismatch between the server and client, please check you have the correct version of the modpack and that you're not playing in a cracked launcher
