### ISSUE TITLE
crash ModPack proeminance 2

### ISSUE THREAD

**Issue by totor667** [LunaPixelStudios/Prominence#112]
### Describe the Bug

The crash world when building the item emerald breastplate on MC dungeon armors mode

### Reproduction Steps

1.
2.
3.
...
craft emerald breastplate and wear the breastplate

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/140307628/a4244d94-7d66-4515-9a07-a88f26df8012)

### Crash Report or Log

net.minecraft.client.world.WlientWorld.getRegistryManager()

### Operating System

windos 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

proemiance 2

### Optifine

I used Optifine

### Other Mods

auncun autre mods n'a était ajouté

**Comment by nvb-uy** [comment]
Update all the trims
