### ISSUE TITLE
Item duplication due to ore unification.

### ISSUE THREAD

**Issue by ThePiekar** [LunaPixelStudios/Prominence#115]
### Describe the Bug

Copper blocks have been replaced by cut copper blocks, where the latter takes all crafting recipes of the former.
This wouldn't be a problem (outside of the regular copper block being much harder to obtain and required for the eden ring portal) if regular copper blocks didn't craft into four cut copper blocks in the stone cutter. 

This makes the cut copper blocks itself craftable into four cut copper blocks, creating a powerful item duplication mechanic.

On top of this regular copper blocks seem to be obtainable only via the uncrafting table from twilight forest, which is a shame.

### Reproduction Steps

1. Craft cut copper block (9 copper ingots)
2. Place it into the stone cutter 
3. Craft 4 cut copper blocks 
4. Repeat for infinite copper

### Operating System

Linux mint

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence I 1.8.0 

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed
