### ISSUE TITLE
Game Crash due to Armor 

### ISSUE THREAD

**Issue by manikigaming** [LunaPixelStudios/Prominence#117]
### Describe the Bug

Game crashes when putting Cincinnasite Chestplate in Crafting Table

Discovered while testing online server using Prominence II Fabric 1.20.1 
Replicated in Solo World (offline)

Works fine equipped, crashes when placed in crafting table
Assuming it has something to do with it being rendered as floating above the Workbench due to Visual Workbench or smth

### Reproduction Steps

1. Craft Cincinnasite Chestplate
2. Place in Crafting Table
3.  Game crashes immediately 
...

### Screenshots and Videos

https://youtu.be/7X-j_-UkHIw

Uploaded a video of the crash

### Crash Report or Log

https://pastebin.com/im0FWmqf

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Prominence II [FABRIC] Fabric-loader-0.14.21-1.20.1

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed in latest version
