### ISSUE TITLE
Unlimited arrows/arrow duping from Supplementaries

### ISSUE THREAD

**Issue by ClayBCE** [LunaPixelStudios/Prominence#12]
### Describe the Bug

If you equip a Quiver from Supplementaries, it will pull from all the arrows stored within without actually deducting the amount, allowing you to have unlimited arrows of any type.

### Reproduction Steps

1. Put any arrow type into Quiver.
2. Shoot arrows.
3. Collect shot arrows off the ground, thus duping them.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.6

### Optifine

No

**Comment by nvb-uy** [comment]
Is this without any enchantments in the bow?

**Comment by ClayBCE** [comment]
> Is this without any enchantments in the bow?

After testing further, the problem seems to be with the Hunting Bow from Meadow. Default bow seems to deduct arrows properly.
