### ISSUE TITLE
MythicMobs Drake Testure Black

### ISSUE THREAD

**Issue by Standard-Issue-Username** [LunaPixelStudios/Prominence#121]
### Describe the Bug

Drake texture displays correctly in Guide Book but is black in world.

Just updated to v.0.6.0, new world.

### Reproduction Steps

1. Launch new game

### Screenshots and Videos

![2023-07-30_11 31 38](https://github.com/LunaPixelStudios/Prominence/assets/140969815/7a0491e8-b078-40dd-964d-c2a5084ca203)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

0.6.0

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed
