### ISSUE TITLE
Game crashes while trying to apply resourcepack

### ISSUE THREAD

**Issue by nikiforr** [LunaPixelStudios/Prominence#122]
### Describe the Bug

When I try to somehow change the resourcepack, turn it off, add the new one or change the order, when I confirm changes the game crashes.

### Reproduction Steps

1. Do anything with resourcepacks
2. Click "Done"

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v1.0.3hf

### Optifine

No

**Comment by nvb-uy** [comment]
Update modernfix
