### ISSUE TITLE
Lan not working

### ISSUE THREAD

**Issue by ShadowFauxlFoxl** [LunaPixelStudios/Prominence#123]
### Describe the Bug

E4MC does not re add the "Open To Lan" button when installed
![image](https://github.com/LunaPixelStudios/Prominence/assets/81649395/2ba372ac-df05-41f3-9a10-c662311b535b)

### Reproduction Steps

1.Installed E4MC
2. Run The game, and join a world
3. the Open to Lan button does not exist
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence 1 Fabric , 2.0.0

### Optifine

No

### Other Mods

No

**Comment by ShadowFauxlFoxl** [comment]
I forgot I added Immersive MC, for VR help

**Comment by nvb-uy** [comment]
e4mc is not yet supported in Prominence, we plan on doing so soon. Please use the serverpack to make a local server in the meantime, or alternatively if you only need to enable cheats, use NBTStudio
