### ISSUE TITLE
Prominence 2 video settings menu problem

### ISSUE THREAD

**Issue by DownrangeEIGHT8** [LunaPixelStudios/Prominence#124]
### Describe the Bug

The on and off settings in the video settings dont have a check mark to show if they are enabled or disabled so i cant see what is enabled or not

### Reproduction Steps

1.Open pause menu
2.go to settings
3.video settings

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/141265422/c8c826b4-fde5-4737-bc53-c9f7e4d9386a)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence II [Fabric] v0.6.0 minecraft version 1.20.1

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed in latest version
