### ISSUE TITLE
Stripped Aurel Wood block drops nothing when mined

### ISSUE THREAD

**Issue by DeDog103** [LunaPixelStudios/Prominence#126]
### Describe the Bug

The Stripped Aurel Wood block from "Paradise Lost" does not drop when mined. Keep in mind that I mean the wood with all 6 sides covered up by bark. 

### Reproduction Steps

1. Get Stripped Aurel Wood
2. Go into survival
3. Mine said bloq

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

2.0.1

### Optifine

No

**Comment by nvb-uy** [comment]
Nothing in the packs edit those loot tables so it's probably an issue in the mod's end, please report it in their github tracker
