### ISSUE TITLE
Crash while generating chunks

### ISSUE THREAD

**Issue by KyleBeep** [LunaPixelStudios/Prominence#127]
### Describe the Bug

Server completely crashes while loading new terrain

### Reproduction Steps

1.make world
2. generate new terrain
3.
...

### Crash Report or Log

https://pastebin.com/MusuFMRB

### Operating System

Windows 10/ server running on ubuntu pterodactyl

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v1.0.3

### Optifine

No

### Other Mods

Yung's Better Desert Temples, Yungs better ocean monuments.  Removed better combat, end remastered, and better combat addon. these were removed before world creation

**Comment by nvb-uy** [comment]
Please do not make issues if you have modified the pack. If you modify the modpack, do it at your own risk, but if the issue isn't on an official version then we won't help here. You may open a post in the modded-mc-discussion channel at our discord.
