### ISSUE TITLE
Crash / Boss

### ISSUE THREAD

**Issue by Cookie399** [LunaPixelStudios/Prominence#128]
### Describe the Bug

Prominence II 1.20.1 Fabric Crash in Archon mod the Fire Boss [ during the attack ]

### Reproduction Steps

1.
2.
3.
...

### Operating System

W 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v0.7.0

### Optifine

No

**Comment by Cookie399** [comment]
![Uploading Képernyőkép 2023-08-07 113355.png…]()

**Comment by nvb-uy** [comment]
Send logs

**Comment by Cookie399** [comment]
[[203658] [Render threadINFO] [bclib.txt](https://github.com/LunaPixelStudios/Prominence/files/12328090/203658.Render.threadINFO.bclib.txt)

**Comment by Cookie399** [comment]
https://www.youtube.com/watch?v=CrzAzlhUe-E

**Comment by nvb-uy** [comment]
Report it to Archon's github tracker
