### ISSUE TITLE
Quests bug

### ISSUE THREAD

**Issue by rostyslavmm** [LunaPixelStudios/Prominence#129]
### Describe the Bug

Sometimes when i have an item, questbook doesnt see it/ even if i throw it and pick up againe

### Reproduction Steps

1.Go by the quest line
2. My questbook dont see that i have a hammer for ad astra mod
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/141637144/9bf4dc94-3613-42aa-92e2-30412fd9bedf)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v0.7.0

### Optifine

No

**Comment by AlexMarsev666** [comment]
The essence of the bug is that the "nbt" argument does not work correctly. I'm not sure that if you delete it everywhere, everything will work correctly

**Comment by nvb-uy** [comment]
Fixed in v0.8.0
