### ISSUE TITLE
Prominence server crash 

### ISSUE THREAD

**Issue by GhostRider6070** [LunaPixelStudios/Prominence#131]
### Describe the Bug

whenever I load into my server it crashes and kicks me out because I picked up a boat with the "carry on" mod and mounted my mythical creature. tired this on single player and it corrupts the world. the reason it happens is because a boat is placed on the mount while you try getting on mounts

### Reproduction Steps

1.pick up boat with "carry on"mod
2. Mount any mob that can use a saddle
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Prominence FABRIC 2.0.1

### Optifine

I used Optifine

### Other Mods

no

**Comment by nvb-uy** [comment]
Report it to the carryon issue tracker
