### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by Discordian23** [LunaPixelStudios/Prominence#133]
### Describe the Bug

the game crashes with a JEI interaction

### Reproduction Steps

1.Press E
2. click the text box in the bottom right corner
3. type @gate
4. Crash

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

current

### Optifine

No

### Other Mods

no

**Comment by nvb-uy** [comment]
Update to the latest version of the modpack
