### ISSUE TITLE
Waystones/Portals Sending to 0,0

### ISSUE THREAD

**Issue by AriaThePeryton** [LunaPixelStudios/Prominence#135]
### Describe the Bug

Waystones and Portals keep sending me to world spawn/0,0 Cords every time I try to cross-dimension travel.
This only started AFTER visiting the Minecell dimensions (and kill the boss located within)
Those in the server who have also visited/Finished Minecell have also had the issue.

### Reproduction Steps

1.Visit the Minecells Dimensions
2.Kill conjunctivius
3.Use a portal/waystone to Visit another Dimension
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence I v2.0.1

### Optifine

No

### Other Mods

Custom Player Models
Better Than Mending

**Comment by nvb-uy** [comment]
Open an issue in their github trackers, it's likely an incompatibility between those mods
