### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by darlan4e** [LunaPixelStudios/Prominence#137]
### Describe the Bug

I pick up the item that is needed for the quest, but it does not count

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

0.7.0

### Optifine

No

**Comment by pysklo** [comment]
The issue also effects Minecraft version 1.20.1.

**Comment by nvb-uy** [comment]
Looking into it

**Comment by nvb-uy** [comment]
Fixed
