### ISSUE TITLE
Enchantment table not working with zenith bookshelves

### ISSUE THREAD

**Issue by Riventis** [LunaPixelStudios/Prominence#14]
### Describe the Bug

Zenith bookshelves don't increase enchantment levels, also enchantment table doesn't show zenith stats, while Jade shows that stats are incresed. Removing EasyMagic for testing made it work again.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.6

### Optifine

No

**Comment by nvb-uy** [comment]
fixed in 1.6.1
