### ISSUE TITLE
How to OPEN local server ?

### ISSUE THREAD

**Issue by Gr4childo-code** [LunaPixelStudios/Prominence#140]
### Describe the Bug

there is no open multiplayer button

### Reproduction Steps

there is no open multiplayer button

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v0.8.0

### Optifine

I used Optifine

**Comment by FugitiveFPS** [comment]
having same issue. Is there a fix?

**Comment by Lonick32** [comment]
Yeah it's pretty annoying and I'm not willing to download a server and run it just for one player to join

**Comment by nvb-uy** [comment]
Remove any extra mods that you added. LAN is not supported.
