### ISSUE TITLE
Grievous Wounds deleting graves/killing creative v1.8.0

### ISSUE THREAD

**Issue by FluffyHuskyTTV** [LunaPixelStudios/Prominence#141]
While running a P1 Private server. some members encountered a skeleton shooting potion arrows giving the effect "grievous wounds"

upon succumbing to the effect (death by potion) their graves never spawned.

Upon testing the effect. players killed with it but not by it spawn graves.

within 4 seconds, I myself in creative also died and lost inventory.

Server Version 1.8.0

Player version 1.8.0 V2

Please note. we didnt want to start over or risk corrupting our world and we started at 1.8.0
Updating may fix this bug but we wish to not risk losing progress or the entire save.

Replication in v1.8.0v2 (newest 1.8.0):

Apply effect : Grievous wounds with items in inventory and/or Creative
Wait for death

return to death location.

[latest (1).log](https://github.com/LunaPixelStudios/Prominence/files/12361734/latest.1.log)

**Comment by FluffyHuskyTTV** [comment]
Addendum: Effect also known as "Healing Reduction" i cannot find the source mod

**Comment by nvb-uy** [comment]
Fixed
