### ISSUE TITLE
Questbook - Quest overview gives "Failed to parse tag text" error

### ISSUE THREAD

**Issue by AtraNoctua** [LunaPixelStudios/Prominence#144]
### Describe the Bug

I am unsure if this a bug comparable to #137 but I'd file a new one with some more details that I found. I went to through the logging and may have found something relevant. Please find pictures and logging attached to the ticket.

Note: Minecraft Version 1.20.1

### Reproduction Steps

1. Start fresh world
2. Open Questbook (through actual book, or U)
3. Click on a quest (starter quest for me)
4. Under "Overview" it now displays "Failed to parse tag text"
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/142658409/529ab8ca-ddbd-4603-9985-4c2d2d4869a8)

![image](https://github.com/LunaPixelStudios/Prominence/assets/142658409/d4a15622-633b-479a-8c6a-82c484e47971)

### Crash Report or Log

https://pastebin.com/jSGwk7xL

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v0.8.0

### Optifine

No

**Comment by SlugFilth** [comment]
Also seeing this on Prominence II / forge 1.20.1/ v0.7, same steps to reproduce.

https://paste.atlauncher.com/view/a4980fca-ba2e-4864-944f-81b5abab39ed

**Comment by TrevorShelby** [comment]
+1

**Comment by Fidixx** [comment]
+1

**Comment by nvb-uy** [comment]
Known issue, it's related to Heracles and only happens in windows, please wait for a fix from their end.

**Comment by Fidixx** [comment]
can you please post the link to the Problem in Heracles.
I can´t find the Bug there.
thx Fidixx
