### ISSUE TITLE
No EU server for Prominence 2 

### ISSUE THREAD

**Issue by Bl4nkkk** [LunaPixelStudios/Prominence#147]
### Describe the Bug

Why is there no server for EU people, in other modpack is a eu server, but for this not. Pls ad a eu server for  better ping 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Win. 11 

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence 2 1.20.1

### Optifine

No

**Comment by nvb-uy** [comment]
Our dedicated server is in the US, it is not cheap and we cannot simply move to EU because of some users. This is also not related at all to the modpack itself.
