### ISSUE TITLE
Server spam after updating modpack

### ISSUE THREAD

**Issue by drag0n1zed** [LunaPixelStudios/Prominence#148]
### Describe the Bug

After updating the modpack from v1.8.0 to v2.0.1 (which removed playerEX), the server now spams the message 
`[Server thread/WARN]: Failed to deserialize component: unregistered key playerex:experience_data`
and
`[Server thread/WARN]: Failed to deserialize component: unregistered key respawnablepets:respawnable`
 a lot and it is taking up a lot of the very limited storage space I have.

### Reproduction Steps

1. Update the modpack from v1.8.0 to later version without resetting the world.
2. Start server.
3. Spam.
...

### Screenshots and Videos

no need

### Crash Report or Log

https://gist.github.com/drag0n1zed/948a2666055a76493bac2bed93cec14f

### Operating System

The server uses docker openjdk on Linux

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v2.0.1

### Optifine

No

### Other Mods

[EasyAuth](https://modrinth.com/mod/easyauth/version/uT6sA486)
[Create Chunkloading](https://www.curseforge.com/minecraft/mc-mods/create-chunkloading)
[Simple Voice Chat](https://modrinth.com/plugin/simple-voice-chat/)
[FTB XMod Compat (how is this not already in the modpack)](https://www.curseforge.com/minecraft/mc-mods/ftb-xmod-compat)
[TabTPS](https://modrinth.com/plugin/tabtps)
[FabricTailor](https://www.curseforge.com/minecraft/mc-mods/fabrictailor)

**Comment by nvb-uy** [comment]
Add it to logbegone config, it's because of the removal of playerex.
