### ISSUE TITLE
Quest system not working

### ISSUE THREAD

**Issue by Mefuuu** [LunaPixelStudios/Prominence#150]
### Describe the Bug

When clicking on any quest, there is "Failed to parse tag text" message every time and i can't complete any quest

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/42370647/9a8a8322-2083-428a-b509-455073abc036)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence II 0.9.5

### Optifine

No

**Comment by nvb-uy** [comment]
Windows-specific bug, duplicated issue, not game-breaking, you can still use the tasks
