### ISSUE TITLE
Prominence II [FORGE] - Quest Log - Failed to parse tag text

### ISSUE THREAD

**Issue by Xinterp6196** [LunaPixelStudios/Prominence#154]
### Describe the Bug

When opening the quest log (Quest Book), the game fails to parse tag text.

### Reproduction Steps

1. Open quest log
2. Click on first quest
3. Fails to parse tag text (Cannot progress past this point)

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/103495470/0e4df784-c87e-44ae-b2e7-c5531d1d36da)

### Crash Report or Log

https://pastebin.com/ZcnJA1pi

### Operating System

Windows 10 - MC Version 1.20.1

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Prominence II [FORGE] v0.9.0

### Optifine

No

### Other Mods

No additional mods have been installed outside of what is included with the modpack.

**Comment by nvb-uy** [comment]
Known bug, only happens on windows and it's fault of the questing mod
