### ISSUE TITLE
Prominence I fabric: [Render thread/ERROR]: Calling server config when it is not yet available! This is a bug! Message: Config data is missing java.lang.Exception: Config not yet available

### ISSUE THREAD

**Issue by drag0n1zed** [LunaPixelStudios/Prominence#155]
### Describe the Bug

When one of my players tries to join the server, this error happens:
"[Render thread/ERROR]: Calling server config when it is not yet available! This is a bug! Message: Config data is missing
java.lang.Exception: Config not yet available" (full log below)
Other players (including myself) are able to join.

### Reproduction Steps

1. Install modpack
2. Join server
3. get kicked
...

### Screenshots and Videos

![F0715@JQ`JJQQOEI8X5B2MI](https://github.com/LunaPixelStudios/Prominence/assets/62168687/25e15d19-33e2-4e97-a942-6f627cba5b96)

### Crash Report or Log

https://gist.github.com/drag0n1zed/569c80ac829d96884e884c29127a1d80

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v2.0.1

### Optifine

No

### Other Mods

none

**Comment by nvb-uy** [comment]
You didn't install the modpack correctly, please read #faq in our server for a tutorial on modpack installation
