### ISSUE TITLE
1.0.0 Crashing due to ConcurrentModificationException

### ISSUE THREAD

**Issue by douglasg14b** [LunaPixelStudios/Prominence#156]
### Describe the Bug

Happens when traveling & loading chunks.

Appears related to `ThreadedAnvilChunkStorage`?

### Reproduction Steps

1. Start new  single player server
2. Explore till it crashes

### Crash Report or Log

https://pastebin.com/Fd3zBvgf

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

1.0.0

### Optifine

No

**Comment by nvb-uy** [comment]
Can't repro
