### ISSUE TITLE
Questing system broken

### ISSUE THREAD

**Issue by waeesd123** [LunaPixelStudios/Prominence#157]
### Describe the Bug

For the task to complete i need to drop the item and pick it up however crafting it and sending straight to inventory doesn't complete the task. Prominence II modpack, clicking report bugs and issues sends me here to prominence.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.0.0

### Optifine

No

**Comment by nvb-uy** [comment]
Heracles issue, drop it and pick it up
