### ISSUE TITLE
Trying to load prominence v1.0.0 on ATLauncher causes it to crash whilst starting up

### ISSUE THREAD

**Issue by Ch1ckenLover21** [LunaPixelStudios/Prominence#158]
### Describe the Bug

It starts launching then crashes after a few seconds (the minecraft version is 1.20.1 it just gives me 1.19 as an option)

### Reproduction Steps

1.press play
2.get into the launch
3.game crashes
...

### Crash Report or Log

https://paste.atlauncher.com/view/d27b027a-aba3-43b4-be85-240f50949b59

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Prominence II [FORGE] v1.0.0

### Optifine

No

**Comment by nvb-uy** [comment]
Do not play older versions, those are months old.
