### ISSUE TITLE
Profession incompatibility issues with Create

### ISSUE THREAD

**Issue by samishoux** [LunaPixelStudios/Prominence#16]
### Describe the Bug

The profession mod has currently a compatibility issue with the mod create. tested on v1.5 & v1.6.

This bug occurs sometimes when the deployer of create attempts to place a sapling through a block.
When this happens no player entity exists but the profession's mod does not expect this behaviour to happen thus crashing the modpack.

note: If a deployer exists and has many saplings, the save is doomed since the modpack will crash when the world load.

[issue related](https://github.com/ExcessiveAmountsOfZombies/Professions/issues/18#issuecomment-1562196471)

[example video](https://media.giphy.com/media/1bMqhI6Jfpvw1M3zpI/giphy.gif)

[crash report](https://pastebin.com/G2tbYk9P)

### Reproduction Steps

1. place a deployer facing up
2. give the deployer a source of power (creative works fine)
3. place a dirt block above the deployer
4. give the deployer a sapling
5. if the bug does not occur right away try to break the sapling and give the deployer more than one sapling

### Screenshots and Videos

[example video](https://media.giphy.com/media/1bMqhI6Jfpvw1M3zpI/giphy.gif)

### Crash Report or Log

[crash report](https://pastebin.com/G2tbYk9P)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Tested on v1.5 & v1.6

### Optifine

No

**Comment by jmadarg** [comment]
Can you test if adding the [Neruina](https://www.curseforge.com/minecraft/mc-mods/neruina) mod helps?

**Comment by samishoux** [comment]
Can confirm it still crashed but with a different crash log
[https://pastebin.com/LzC8EF52](https://pastebin.com/LzC8EF52)

**Comment by nvb-uy** [comment]
Professions will get removed in v1.6.2
