### ISSUE TITLE
No shaders

### ISSUE THREAD

**Issue by haysine** [LunaPixelStudios/Prominence#160]
### Describe the Bug

shaders menu completely gone

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/144489264/b2598522-f6f4-4632-9ce3-74da71ed51fb)

### Operating System

Windows 10 

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v1.0.0

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
Update the modpack
