### ISSUE TITLE
Better MC [PLUS] - 1.18.2 v1.0.0 - Crashes on starting after update - ATLauncher

### ISSUE THREAD

**Issue by Fraz1402** [LunaPixelStudios/Prominence#162]
### Describe the Bug

I opened the launcher, started the game and was prompted to update the instance. I updated the instance and started the game again. It started to load but then crashed. 

### Reproduction Steps

1.
2. 
3.
...

### Crash Report or Log

https://gist.github.com/Fraz1402/f310ad2b308def9e76b0b71e39bedee6

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [PLUS] - 1.18.2 (Better MC [PLUS] - 1.18.2 v1.0.0)

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
This is not the place for BMP reports.
