### ISSUE TITLE
Just enough items crash

### ISSUE THREAD

**Issue by TomM4444** [LunaPixelStudios/Prominence#163]
### Describe the Bug

When I open the Inventory and go to page 69 in the just enough items window, minecraft crashes.

### Reproduction Steps

1.Make a world 
2. Open the inventory 
3. Go to page 69
...

### Crash Report or Log

https://gist.github.com/TomM4444/70790260481a7a39fbe0f58af09c3cff

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v2

### Optifine

No

**Comment by nvb-uy** [comment]
Report to the building gadgets issue tracker
