### ISSUE TITLE
Choice Reward.   In new Tech Reborn quest tree

### ISSUE THREAD

**Issue by WiseSoul881** [LunaPixelStudios/Prominence#164]
### Describe the Bug

New Tech Reborn Quest tree.  
I've found 4 achievements the give "Choice Reward"
1. Overclocker Upgrade
2. Muffler Upgrade
3. Energy Storage Upgrade
4. Compressor

When  I click to claim reward it brings up window with Header "Choice Reward" but box is blank (nothing to pick)

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Capture](https://github.com/LunaPixelStudios/Prominence/assets/137639135/51a9d8ce-df1a-4115-97f6-76e33dc0a389)
![Capture1](https://github.com/LunaPixelStudios/Prominence/assets/137639135/628aea64-bfd6-4501-b2f0-bbfa983031cf)
![Capture2](https://github.com/LunaPixelStudios/Prominence/assets/137639135/59bc251e-0954-4740-b028-9e5688177f83)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Prominence I (Fabric) 2.1.0

### Optifine

I used Optifine

**Comment by WiseSoul881** [comment]
Not Forge and Not Optifine....   

Almost done with Tech Reborn tree everything else works fine.....Thx for all you do!

**Comment by nvb-uy** [comment]
Fixed as of latest

**Comment by nvb-uy** [comment]
Do not open another issue, it was closed because it was already fixed, the prom 1 quest overhaul update isn't out yet.
