### ISSUE TITLE
Prominence 2 v1.2.0 duplicate ores spawning from multiple diffrt mods (Lead, Silver, Bauxite)

### ISSUE THREAD

**Issue by Dardade** [LunaPixelStudios/Prominence#166]
### Describe the Bug

Even after the 1.2.0 version update, there are still some duplicate ores spawning underground from different mods.
These include 3 Lead Ores (from Tech Reborn AND Industrial Revolution AND Modern Industrialization), 2 Silver Ores (Bewitchment AND Tech Reborn), 2 Bauxite Ores (Tech Reborn AND Modern Industrialization).

There are also 2 types of salt, but these may be acceptable. Both uranium and *uraninite* also exist together which is okay.

### Reproduction Steps

1. Start a new world in Prominence 2, v1.2.0 on FABRIC. Minecraft version 1.20.1 (the other part on this github defaults to Minecraft version 1.19; but this IS Minecraft version 1.20.1)
2. Choose world generation type 'BetterX' (default choice)
3. >These ores all spawn naturally underground together

### Screenshots and Videos

![2023-09-16_22 18 27](https://github.com/LunaPixelStudios/Prominence/assets/76129686/191f83d6-ae09-4167-aae8-f97e97f66ca1)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.2.0

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
Merged in 1.3.0
