### ISSUE TITLE
Disconnecting caused by item "minecraft:filled_map" on a world updated to Prominence V1.2.0 Fabric 1.20.1

### ISSUE THREAD

**Issue by Medusa1338** [LunaPixelStudios/Prominence#167]
### Describe the Bug

First I'd like to say I'm new to reporting bugs in this manner, please let me know if I can add any extra information to help. I was redirected here from the discord.

After updating my 1.20.1 Fabric server to Prominence v1.2.0 I could not reconnect, getting the error message "Internal Exception: java.net.SocketException: Connection reset". After trying the following: restarting my PC, restarting the server, reinstalling server JAR files and configs, and reinstalling a new Prominence 2 profile I was still unable to reconnect to the server. The world itself has remained the same throughout (maybe just a corrupted world?) and all other players were unaffected.

This then happened to another player on my server after he picked up a map from a personal loot chest. We decided to remove the item labeled "minecraft:filled_map" from our inventories using NBTExplorer and were once again able to connect to the server without issue.

As soon as the item is picked up (and when trying to reconnect) the server console reads out a giant list of errors which I copied and attached here. I can provide a full log if needed. The client and server never actually crashed so I have no crash report to give that I know of. The errors in question all start with something along the lines of "[Server thread/ERROR]: Mixin apply for mod moonlight failed [...]"

### Reproduction Steps

1. Find a "Buried Treasure Map" item in a personal loot crate. The one I found and successfully recreated the bug with has the following NBT tags: #vivecraft:maps, #minecraft:trim_materials and Minecraft.
2. Put it into your inventory.
This did not happen when I tried giving myself a generic filled map. 

### Screenshots and Videos

![2023-09-17_04 07 08](https://github.com/LunaPixelStudios/Prominence/assets/145256295/c513f0fe-5917-4e3d-960b-aa8adb75010a) ==> The item and it's detailed item description.
![2023-09-17_04 07 22](https://github.com/LunaPixelStudios/Prominence/assets/145256295/454e82b1-587e-4482-9aeb-0b171c157cc8) ==> The resulting crash screen.
![2023-09-17_04 38 00](https://github.com/LunaPixelStudios/Prominence/assets/145256295/fbd52ca6-15cb-45de-9d61-4500d9eb6aef) ==> Error message when trying to re-join the server.

### Crash Report or Log

https://pastebin.com/VtJ8xPxS

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.2.0 (Minecraft 1.20.1)

### Optifine

No

**Comment by Dylogic** [comment]
Hey i been having the same problem as you, but for me it only kicked me out when i right clicked with the map in my hand, since then i am unable to join my friends server.

**Comment by Medusa1338** [comment]
Hi,
You can do what I did (find your player data in the world folder and remove the item with NBTExplorer) or update the Moonlight Lib mod in your mods folder to the latest version, as this seems to be the issue.

Others have been having this issue as well. I have heard that the Moonlight Lib developers have released a fix as of yesterday. https://github.com/MehVahdJukaar/Moonlight/issues/147

The current version of this pack uses Moonlight Lib version 2.8.23 which is the bugged version.

**Comment by nvb-uy** [comment]
As [Medusa1338](https://github.com/Medusa1338) said, update moonlightlib or update to v1.3.0 (will release today)
