### ISSUE TITLE
Vein Miner and Grindstone

### ISSUE THREAD

**Issue by Uchi112** [LunaPixelStudios/Prominence#168]
### Describe the Bug

The vein Miner enchant is not working 
also grind stones not letting me ripe the enchant to books 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Promenece II

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
Duplicate of https://github.com/LunaPixelStudios/Prominence/issues/151 

Grindstone was disabled due to a dupe
