### ISSUE TITLE
Deflecting Fireballs Crashes Server

### ISSUE THREAD

**Issue by koukimonster91** [LunaPixelStudios/Prominence#17]
### Describe the Bug

i was running around the nether when i ran into a ghast. i deflected a couple fireballs with no problem, i missed both them. i was then falling when i deflected the 3rd one(possible crit) and that was when the server crashed and now it crashes everytime i spawn back in. i was using one of the nicer simply swords swords when it happened.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/7amRcpwQ

### Operating System

Ubuntu 22.04.2

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.6

### Optifine

No

### Other Mods

none

**Comment by koukimonster91** [comment]
ElRufian#3591 from the discord channel also had the same issue and they used a runic twin blade from simply swords and they were also falling when theirs crashed

**Comment by koukimonster91** [comment]
i installed Neruina on my server and that allowed me to load into the world before the crash. that gave me enough time to be able to spam the command "kill @e[type=fireball]" into my server console and doing that removed the problematic fireball and stopped the crash. i will try to reproduce this issue tomorrow and update my findings.

**Comment by koukimonster91** [comment]
was just able to successfully reproduce the issue using a vanilla sword while standing still. to reproduce just deflect a fireball back at a ghast, the crash occurs when you hit the ghast with it. i also tested it on a fresh server install with a fresh character and it also crashed

**Comment by nvb-uy** [comment]
fixed in 1.6.1
