### ISSUE TITLE
music discs consumed and wont play when using jukebox

### ISSUE THREAD

**Issue by OMGitsdezaire** [LunaPixelStudios/Prominence#170]
### Describe the Bug

I tried inserting the disc from Ars Nouveau: 'Thistle- The Sound of Glass' into a Jukebox and it didn't start playing the music for some reason. I tried doing the same thing with a regular Minecraft music disc and the same result. (version 1.20.1)

### Reproduction Steps

1. Place Minecraft Jukebox
2. Insert Minecraft Music Disc
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v1.1.0

### Optifine

No

**Comment by JiNama** [comment]
Same behavior on Fabric

**Comment by nvb-uy** [comment]
Duplicated, fixed in the next update.
