### ISSUE TITLE
Handcrafted texture bug & fps drop

### ISSUE THREAD

**Issue by SerUameN** [LunaPixelStudios/Prominence#171]
### Describe the Bug

Prominence II [Fabric] v1.2.0-1.20.1
Weird texture of handcrafted beds and huge fps drop when searching for handcrafted items in rei.

### Screenshots and Videos

![2023-09-17_22 24 08](https://github.com/LunaPixelStudios/Prominence/assets/100700897/9969383c-c874-4db7-a9e1-a356cd944919)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.2.0

### Optifine

No

**Comment by nvb-uy** [comment]
Closing because it's already been opened for a month in Handcrafted's github and the developers are already working in a fix.
