### ISSUE TITLE
Server Crash while flying

### ISSUE THREAD

**Issue by Kiwicast** [LunaPixelStudios/Prominence#172]
### Describe the Bug

Server Crashed while flying around looking and testing.

### Reproduction Steps

1. Went into creative and started flying around
2. Server Crashed
3.
...

### Crash Report or Log

https://pastebin.com/zbCE5gaD

### Operating System

Windows but Linux Dedicated Server using Pterodactyl

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.2.0

### Optifine

No

### Other Mods

Standard Modpack didn't use anything else. Prominence II 1.2.0 - Fabric 1.20.1 Loader: 0.14.22

**Comment by nvb-uy** [comment]
Fixed in v1.3.5 (Releasing today)

**Comment by Kiwicast** [comment]
Unfortunately this was for Fabric, update was for Forge only?

**Comment by nvb-uy** [comment]
The fabric update will be released today ^^ in a couple hours

>

**Comment by Kiwicast** [comment]
ok thank you. appreciate the fast response
