### ISSUE TITLE
Flying in twilight forest ice biome and crashing

### ISSUE THREAD

**Issue by Artic007** [LunaPixelStudios/Prominence#174]
### Describe the Bug

I am crashing every time I enter a server. the crash report is telling me that the issue is me floating in a biome and it being unable to load a texture
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "twilightforest.client.TFShaders$PositionAwareShaderInstance.invokeThenEndTesselator(int, float, float, float)" because "twilightforest.client.TFShaders.AURORA" is null

### Reproduction Steps

1. use the ars Nuovea spell launch
2. in the ice biome of the twilight forest
3. crash game
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

47 1.3

### Optifine

No

### Other Mods

N/A standard Prometheus 2

**Comment by Seegras** [comment]
Same here, after leaping in with an ars nouveau spell. 
```

[18:16:09] [Render thread/ERROR] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "twilightforest.client.TFShaders$PositionAwareShaderInstance.invokeThenEndTesselator(int, float, float, float)" because "twilightforest.client.TFShaders.AURORA" is null
	at twilightforest.client.TFClientEvents.renderWorldLast(TFClientEvents.java:172)
```

Now I can't load the save anymore, since this always happens.

**Comment by Seegras** [comment]
Moved myself away using NBTedit. Tried again approaching the Snow Queen, this time on foot. 
Crashed on reaching the top of the ice shelf. So it's not a general problem, not related to ars or flying.

**Comment by Katuhrina** [comment]
Just encountered this same problem on my server. I have no idea how I'm going to fix it either. I'm lost.

**Comment by zhiqinLT** [comment]
me too

**Comment by Seegras** [comment]
the problem appears to have been solved in the newest version 1.3.5 of the modpack.

**Comment by nvb-uy** [comment]
Fixed in the latest version

**Comment by MefjuS22** [comment]
same thing happened to me on 1.4.0, so bug still persists
