### ISSUE TITLE
neruina locked me out of my world

### ISSUE THREAD

**Issue by unknwonso** [LunaPixelStudios/Prominence#175]
### Describe the Bug

idk if it the no ui model with id  owo config ui thing but. neruina kicked me out due to ticking exception on the player and it says to remove the culprit mod or contact admin (singleplayer). what happened prior was i was in a sunken/underwater village looting a chest. where i picked up a buried treasure map, closed the chest and saw the map. the map proceeded to be blank so i checked the chest where it proceeded to crash my game. i try to open it up but the neruina is hard locked me out of the world. cant remove a vanilla item so im lost 

### Reproduction Steps

1.pick up a buried treasure map from a chest (it will be blank)
2.while having the map in your hand right click (open) the chest
3. crash 
...

### Screenshots and Videos

N/A

### Crash Report or Log

https://gist.github.com/unknwonso/a1d343f74fd11aef36df233da2314933

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.2.0

### Optifine

I used Optifine

### Other Mods

N/A

**Comment by nvb-uy** [comment]
Update moonlightlib or wait for the new update today.
