### ISSUE TITLE
3x Ore quest impossible to complete

### ISSUE THREAD

**Issue by aliceingame** [LunaPixelStudios/Prominence#176]
### Describe the Bug

The quest ask for Industrial Revolution dust and we can only process to Modern Industrialization dust (that do not trigger the quest)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.1.0hf

### Optifine

No

**Comment by nvb-uy** [comment]
Update the modpack, v1.1.0hf is months old.

**Comment by aliceingame** [comment]
Right now it say that the 1.2 version was released 5 days ago, at least on CurseForge for the Fabric version.
Anyway, I updated and the quest is still impossible to complete because of dust type required is impossible to get.
