### ISSUE TITLE
Inigo Boss Crash

### ISSUE THREAD

**Issue by Avemado** [LunaPixelStudios/Prominence#177]
### Describe the Bug

Disconnect from the server with Prominence II installed, when summoning and fighting the Inigo boss from the Archon mod Internal Exception: net.minecraft.class_148: Exception while adding particle

### Reproduction Steps

1. Use Prominence II version 1.2.0 
2. Summon Inigo
3. Fight Inigo
4. Get error and disconnect while fighting Inigo

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/58288858/c08ec243-15bd-4854-bfad-4e64b6b1d759)

### Operating System

Windows 10/11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.2.0

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
Report to the mod's issue tracker
