### ISSUE TITLE
Server won't start due to Shield Overhaul

### ISSUE THREAD

**Issue by Sajier** [LunaPixelStudios/Prominence#178]
### Describe the Bug

Currently trying to start a server on Apex Hosting after updating to 1.3.0.  Getting Runtime Exception because of shield_overhaul.  I have attached the full log below.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/yvC7DcRJ

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.3.0

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed as of latest
