### ISSUE TITLE
ME system terminal crash

### ISSUE THREAD

**Issue by FinnSetchell** [LunaPixelStudios/Prominence#18]
### Describe the Bug

game crashes when going from largest to smallest terminal size.
Tested in fabric 1.19.2 with just ae2 and did not get the issue

### Reproduction Steps

1. make sure the GUI scale is small enough for the terminal to change size, for example, 3.
2. cycle all the way through the terminal sizes

### Crash Report or Log

https://mclo.gs/92LME9q

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence [FABRIC]-v1.6 (happened in previous versions)

### Optifine

No

**Comment by Savior10K** [comment]
You also crash when you open FTB Quests while in a terminal and press E
https://mclo.gs/WSgBbYG
