### ISSUE TITLE
Missing spell books

### ISSUE THREAD

**Issue by RueShejn** [LunaPixelStudios/Prominence#180]
### Describe the Bug

there seems to be no way of obtaining, crafting, or looting the "paladins & priests" mod spell books and "Wizards" mod spell books. locking you out of 15 useful spells, and only allowing the use of "Invocation" mod and "Archon" mod spells.

this kills builds for mages and dosent allow much freedom at all, and completely destroys the ability to setup healer mage builds.

### Reproduction Steps

1. try to obtain mage books
2. you cant
3. ...
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.2.0 [Fabric]

### Optifine

No

**Comment by nvb-uy** [comment]
You can get them via the spell binding table.
