### ISSUE TITLE
"Failed to Access World" in main menu

### ISSUE THREAD

**Issue by jocafer377** [LunaPixelStudios/Prominence#181]
### Describe the Bug

All of a sudden I cannot access my world which I spent hours on, I tried restarting my pc and repairing profile on curseforge but it still says the same thing "Failed to access world". I am using Prominence Fabric 1.20.1

### Reproduction Steps

1.Launch Prominence 2 Fabric from curseforge
2.Select and enter world from main menu
3.Lastly it returns to main menu and says "Failed to access world"
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/145782897/af6da5e5-61f8-4814-b3ad-8f7145aee076)

### Crash Report or Log

https://gist.github.com/jocafer377/bc77a576be8f8919f981384c6fb8ee39

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.1.0hf

### Optifine

No

**Comment by nvb-uy** [comment]
Try doing a fresh install with the latest version
