### ISSUE TITLE
Went through the Promenade of the condemned portal and the portal out broke

### ISSUE THREAD

**Issue by Xirxed** [LunaPixelStudios/Prominence#184]
### Describe the Bug

I went through the portal at the end of the prisons quarters n then when I turned around there was no portal out.
I don't know if there's any other way to get out but if there is, could you explain on how to?
I might just be slow and there's another way out but I haven't found it yet.

### Reproduction Steps

1.I don't exactly know how to recreate it
2.
3.
...

### Screenshots and Videos

![2023-09-26_03 39 44](https://github.com/LunaPixelStudios/Prominence/assets/146067894/7d1c44a7-0415-4d64-b6c7-68c204fca118)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

-v1.3.0hf.zip

### Optifine

No

**Comment by nvb-uy** [comment]
Update your modpack

Try getting out with a waystone or if not, enabling cheats. Report this to the mine cells issue tracker
