### ISSUE TITLE
Incompatible mods!!!

### ISSUE THREAD

**Issue by cicuadrian** [LunaPixelStudios/Prominence#185]
### Describe the Bug

So.. i installed the modpack from Curseforge (Prominence I [FORGE]) , i clicked play, it started loading and it's not showing the main menu , it's says "You have added a mod that is incompatible with our Modpack! Please remove any extra mods you added to the modpack until this warning disappears.

What do i need to do to fix this ? 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot_2](https://github.com/LunaPixelStudios/Prominence/assets/13074497/d5ecad88-4530-42cd-8872-a8b641cad9a7)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2 FORGE 43.2.23

### Optifine

No

**Comment by Disiduous** [comment]
Current version only has 254 mods, yours is showing 420, maybe you installed something wrong? Delete then reinstall the modpack

**Comment by nvb-uy** [comment]
Do what the warning says, remove any mod you've added.
