### ISSUE TITLE
Modern industrialization book dupe

### ISSUE THREAD

**Issue by Devouring-One** [LunaPixelStudios/Prominence#186]
### Describe the Bug

Just installed server and client (hosted on separate machines obviously.

Modern Industrialization book is created upon respawn each time.

Not game breaking, but annoying.

Prominence II - Minecraft version 1.20.1, it does not let me select proper one.

### Reproduction Steps

1. Die
2. Respawn
3. Check inventory

### Operating System

Windows 10/11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.3.1

### Optifine

No

### Other Mods

fresh install

**Comment by nvb-uy** [comment]
Your server and client config might not match, the book is disabled as of latest

**Comment by Devouring-One** [comment]
It is fresh install of the latest version of your modpack, you need to look into that and fix it, i guess?
