### ISSUE TITLE
Disconnect when attacking and blocking

### ISSUE THREAD

**Issue by Devouring-One** [LunaPixelStudios/Prominence#187]
### Describe the Bug

Attacking while blocking causes client to disconnect.

Prominence II - Minecraft 1.20.1 - can't select proper one in this form

### Reproduction Steps

1. Equip default sword
2. Equip default shield
3. Hold block
4. Press attack

### Operating System

Windows 10/11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.3.1

### Optifine

No

**Comment by nvb-uy** [comment]
Update the shield overhaul mod
