### ISSUE TITLE
Modern Industrialization guidebook reappear in inventory every time i die

### ISSUE THREAD

**Issue by qrick** [LunaPixelStudios/Prominence#189]
### Describe the Bug

Modern Industrialization guidebook reappear in inventory every time i die. 

### Reproduction Steps

1. Create new world
2. Die
3. Check inventory
4. Guidebook appear in inventory

### Screenshots and Videos

https://youtu.be/czod0RIwYFI?t=169

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.3.1

### Optifine

I used Optifine

### Other Mods

Fresh install

**Comment by Devouring-One** [comment]
I have reported same issue and it got closed without investigation:
https://github.com/LunaPixelStudios/Prominence/issues/186

**Comment by nvb-uy** [comment]
> I have reported same issue and it got closed without investigation: #186

It's a duplicate of this issue

**Comment by nvb-uy** [comment]
Fixed in 1.3.5
