### ISSUE TITLE
Xaeros Minimap update checker is enabled

### ISSUE THREAD

**Issue by chorbintime** [LunaPixelStudios/Prominence#19]
### Describe the Bug

Xaeros Minimap update checker is enabled, when it should be disabled

### Reproduction Steps

1. Launch the game

### Screenshots and Videos

https://cdn.discordapp.com/attachments/1101995173430448208/1111270002935472179/image.png

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.6

### Optifine

No

**Comment by nvb-uy** [comment]
fixed in 1.6.1
