### ISSUE TITLE
[Improvement request] Replace Tiered with TieredZ

### ISSUE THREAD

**Issue by 4rgc** [LunaPixelStudios/Prominence#191]
[TieredZ](https://www.curseforge.com/minecraft/mc-mods/tieredz) is a fabric-based fork of Tiered which allows reforging quality on items.
Would be amazing to have that functionality.

**Comment by nvb-uy** [comment]
You might be confused as we are already using TieredZ

**Comment by 4rgc** [comment]
My bad, didn't realize there wasn't a reforging station, and that it's done with an anvil instead. :)
