### ISSUE TITLE
Can't change keybind

### ISSUE THREAD

**Issue by Riivya** [LunaPixelStudios/Prominence#193]
after I update my world from prominence II fabric 1.3.1 to 1.3.5 I can't change my keybind. Despite the change I make in control menu, it still use default in game (example: I change drop item to 'x' but when I press 'Q' it still drop my item)

I tried delete the options.txt and restarting and still have the same issue

**Comment by nvb-uy** [comment]
Cannot reproduce, I use E as my drop key and have no issues with it

Can you try a fresh install? And adding keybindfix

**Comment by Riivya** [comment]
I think I fixed it by either deleting optionsviveprofiles.txt or update it again (to 1.3.6), I tried both at the same time so idk which one fix it but thanks for the suggestion!

> Cannot reproduce, I use E as my drop key and have no issues with it
> 
> Can you try a fresh install? And adding keybindfix
