### ISSUE TITLE
Prominence II - Disabling Resourcepacks after restart

### ISSUE THREAD

**Issue by SerUameN** [LunaPixelStudios/Prominence#196]
### Describe the Bug

Prominence II [Fabric] - v1.3.5
The game keeps turning off all of my added resourcepacks after restart.

### Reproduction Steps

1.Enable Resourcepacks
2.Close game
3.Start game
4.Repeat

### Operating System

Windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

1.3.5

### Optifine

No

**Comment by rhllllll** [comment]
m2

**Comment by nvb-uy** [comment]
Fixed in latest
