### ISSUE TITLE
No backpack improvement option

### ISSUE THREAD

**Issue by s4t8ru** [LunaPixelStudios/Prominence#197]
### Describe the Bug

No backpack improvement option due to blacksmithing table modification. REI writes that placing items is not supported by this recipe and this container

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/91220105/dde11ac2-5ca1-4a6c-bf11-765cadeb7a43)

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.0.0

### Optifine

No

**Comment by nvb-uy** [comment]
Try removing the better smithing table mod and see if that works. This shouldn't be really the cause as it's just a clientside mod but maybe it's just breaking it

**Comment by nvb-uy** [comment]
Recipe was wrong
