### ISSUE TITLE
Prominence I, Choice Reward Empty

### ISSUE THREAD

**Issue by aromatize** [LunaPixelStudios/Prominence#198]
### Describe the Bug

In the Tech Reborn quest line, you get a "Choice Reward" for the Overclocker Upgrade quest. However, the choice screen is simply empty and no reward loads in, which leads to an unclaimed reward notification never going away. The Claim All button doesn't clear it either. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/34048739/604d8380-025b-48fb-8435-c9a752e4991a)
![image](https://github.com/LunaPixelStudios/Prominence/assets/34048739/f4713508-de27-48ec-bbc8-c9590075cae2)

### Operating System

Windows 10

### Minecraft Version

Prominence I 1.19.2

### Modloader

Fabric

### Modpack Version

2.1.0

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed in the next update
