### ISSUE TITLE
BYG biompedia and crafting table buttons are overlapping

### ISSUE THREAD

**Issue by tech4vinay** [LunaPixelStudios/Prominence#2]
**Describe the Bug**
BYG Biompedia and crafting table buttons are overlapping in inventory menus. It is not allowing to click the crafting table button.

**Reproduction Steps**
1. start world
2. hit E – Open Inventory
3. BYG Biompedia and crafting table buttons are overlapping

**Screenshots and Videos**
![image](https://github.com/LunaPixelStudios/Prominence/assets/8615357/9fb60ae2-43ea-489e-a9ae-e4ec5e93b8e4)

**Crash Report or Log**
N/A

**Operating System**
Windows 11 64bit

**Minecraft Version**
1.19.2

**Modloader**
Fabric

**Modpack Version**
Prominence [FABRIC] v1.5

**Optifine**
No

**Other Mods**
N/A

**Comment by chorbintime** [comment]
will be fixed, you can disable it in the byg config in the meantime
