### ISSUE TITLE
Server Setup script issue

### ISSUE THREAD

**Issue by NocturnalSergal** [LunaPixelStudios/Prominence#204]
### Describe the Bug

On RedHat systems (unsure about on ubuntu/etc.)

on Line 16 of the included server steup script, orignally the line reads: source "variables.txt" which throws a file not found error, changing it to source "./variables.txt" resolves the issue on redhat systems.

### Reproduction Steps

1. Download Server pack from curseforge
2. unzip into directory
3. Run included start.sh file
4. Recive error Line 16: varibles.txt not found

### Operating System

RedHat9

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

1.3.5

### Optifine

No

**Comment by NocturnalSergal** [comment]
https://i.imgur.com/8kd9byF.png
(didnt realize my terminal went this far up go windows terminal!)

**Comment by nvb-uy** [comment]
You likely deleted the variables.txt ? I have no issues starting it

**Comment by Griefed** [comment]
Heya @NocturnalSergal,

the create of the tool which made the start scripts here.
I don't have RHEL available to run some tests.
The script expects to be run using bash, as indicated by `#!/usr/bin/env bash` at the start of the file.
If RHEL has the `bash`-command available, try it with that. 

Cheers
