### ISSUE TITLE
Rei not loading modpack version 1.3.5 on a server

### ISSUE THREAD

**Issue by Cazual4d** [LunaPixelStudios/Prominence#211]
### Describe the Bug

Unsure as to what causes it but i cant seen to see any of the item recipes through REI at all, i can see the blocks and items but it seems that rei is broken when it comes to showing the recipes
![image_2023-10-05_132845683](https://github.com/LunaPixelStudios/Prominence/assets/48959960/7db206ff-1d0b-4b70-81cd-342d56705fa2)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Unsure, third party server

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

1.3.5

### Optifine

No

**Comment by nvb-uy** [comment]
fixed in the latest
