### ISSUE TITLE
The bug report template (very likely being) copied from Better Minecraft to this repository has some unsuitable text (which you devs probably forgot to change)

### ISSUE THREAD

**Issue by AlisonHuang777** [LunaPixelStudios/Prominence#214]
![screenshot](https://github.com/LunaPixelStudios/Prominence/assets/51637996/975d9fb7-481f-4b03-9602-f5ee08e1ecd7)

**Comment by nvb-uy** [comment]
Some people do end up installing optifine yes, even though we don't support it and will likely crash
