### ISSUE TITLE
Making fluix dust from AE2 crashes the server

### ISSUE THREAD

**Issue by Theoixis** [LunaPixelStudios/Prominence#22]
### Describe the Bug

Whilst trying to make any amount of fluix dust from dropping an anvil on fluix crystals makes the server go poof

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/SqSFrH6G

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.6

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
Not enough info / Optifine is not supported.
