### ISSUE TITLE
Add FTB XMod Compat

### ISSUE THREAD

**Issue by qrick** [LunaPixelStudios/Prominence#221]
### Describe the Bug

 It will add possibility to check recipes for items from Quest menu (and also add them to REI bookmarks)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

Prominence I 1.19.2

### Modloader

Fabric

### Modpack Version

1.3.6

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
not planned
