### ISSUE TITLE
Mac M1 Air, Exit Code 6

### ISSUE THREAD

**Issue by magana05** [LunaPixelStudios/Prominence#223]
### Describe the Bug

I can load the game, but when I click on create new world it crashes and gives me "Exit Code 6". Not entirely sure what to do😭

### Reproduction Steps

1. Get a MacBook M1 Air
2. Install the mod (Fabric)
3. On the launcher, press play
4. Create a new world, and it will crash 

### Screenshots and Videos

The 40 second video is 140 MB, which is a lot but it won't let me attach it, even when I compress. But the steps I said is exactly how it happened.

### Crash Report or Log

Exit Code: 6

### Operating System

Macbook M1 Air

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

Prominence II [FABRIC]-v1.3.6.zip

### Optifine

No

**Comment by SkoopMan1234** [comment]
remove or diasble the spark mod

**Comment by nvb-uy** [comment]
Use Java 21 with ATLauncher
