### ISSUE TITLE
Explorers journal tab not loading 

### ISSUE THREAD

**Issue by SkoopMan1234** [LunaPixelStudios/Prominence#226]
### Describe the Bug

The information bosses tab has the purple and black texture and i cant see the bosses

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

<img width="1440" alt="Screenshot 2023-10-10 at 9 05 29 PM" src="https://github.com/LunaPixelStudios/Prominence/assets/116921081/4c91379d-6e12-4617-99c3-bd5006b5b487">

### Operating System

Macos Sonoma

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

Prominence II [FABRIC]-v1.3.6hf

### Optifine

No

**Comment by nvb-uy** [comment]
fixed in v1.3.7
