### ISSUE TITLE
No .Jar server files in server-pack. Only powershell

### ISSUE THREAD

**Issue by Hamacho1** [LunaPixelStudios/Prominence#227]
### Describe the Bug

When downloading the latest serverpack I get powershell script files instead of the usual run.bat and .Jar files. This issue persists in both the Forge and Fabric version of the modpack. No issues with other modpacks.

### Reproduction Steps

1. Download serverpack
2. Extract files from zip
3. Powershell files
...

### Screenshots and Videos

![ss](https://github.com/LunaPixelStudios/Prominence/assets/147754647/159c9cc8-5237-4c0b-ad34-4fa4cec8c7d7)

### Operating System

Windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Forge

### Modpack Version

v1.3.6

### Optifine

No

**Comment by nvb-uy** [comment]
It's not an issue, we can't legally distribute the jar files, the scripts will download them from official sources.
