### ISSUE TITLE
Buggy (and deadly) behavior of entering/leaving The Bumblezone

### ISSUE THREAD

**Issue by AlisonHuang777** [LunaPixelStudios/Prominence#231]
### Describe the Bug

Watch the footage first.

https://github.com/LunaPixelStudios/Prominence/assets/51637996/60fed5fb-9ba0-4da4-b755-786168ced8b6

Summary:
- Most of the time, when I entering the Bumblezone, I will get yeeted high up in the air, in survival mode this result in a death by fall damage. Sometimes, it also happens when I leave The Bumblezone.
- If I enter the bee nest/beehive by pushing myself with a piston from the bottom of it, the bee nest/beehive will disappear when I leave The Bumblezone. Can be avoided with entering from other direction, use a ender pearl, or leave The Bumblezone by teleporting (including death).

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Forge

### Modpack Version

1.3.6

### Optifine

No.

### Other Mods

Removed:
- https://www.curseforge.com/minecraft/mc-mods/ironchests
- https://www.curseforge.com/minecraft/mc-mods/falling-tree
- https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

Added:
- https://www.curseforge.com/minecraft/mc-mods/framedblocks
- https://www.curseforge.com/minecraft/mc-mods/chunk-loaders
- https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib
- https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib

**Comment by nvb-uy** [comment]
This doesn't happen with ender pearls so I'm assuming it's intended behavior, I contacted the developer to see more about it though
