### ISSUE TITLE
Encountered issues 1.3.6hf

### ISSUE THREAD

**Issue by Possemaster** [LunaPixelStudios/Prominence#233]
Not gamebreaking just improvements;

Main menu UPDATE button shows wrong modpack patchnotes
Ingame Game menu Report Player button is not anchored and overlaps with other buttons when resizing screen.

**Comment by nvb-uy** [comment]
P2 doesn't have an update checker, the update button you saw was probably from Vivecraft, which will get fixed by next update

The report player button sadly is a limitation from vanilla, I'll see if I can just remove it via a mod.
