### ISSUE TITLE
Game crashes when building a Composter from MineColonies

### ISSUE THREAD

**Issue by w3ricardo** [LunaPixelStudios/Prominence#235]
### Describe the Bug

Game crashes when I try to build a Composter Building from MineColonies. I can craft the item and place it, but when I click on Build Options it crashes, before showing the materials for the building, before I click on Build. I am using the Caledonia layout pack.

### Reproduction Steps

1. Change the layout to Caledonia.
2. Place a Composter.
3. Right click on the block.
4. Click on Build Options.

### Crash Report or Log

https://gist.github.com/w3ricardo/9b6931768a17d6a95e272803544e02ec

### Operating System

Windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Forge

### Modpack Version

v1.3.6

### Optifine

No

**Comment by Ch1ckenLover21** [comment]
Can we please have an update on this, I'm also getting the same issue when trying to upgrade my builders hut

**Comment by w3ricardo** [comment]
I tried updating MineColonies to 240-RELEASE and structurize to 631-BETA and got the same error.
I tried updating MineColonies to 265-BETA, structurize to 655-BETA and domum_ornamentum to 142-BETA and got the same error.

**Comment by w3ricardo** [comment]
Updating the Forgified Fabric API (FFAPI - fabric-api-0.90.0+1.9.27+1.20.1) seems to work.
It seems we are having problems because this modpack mixes forge and fabric mods.
https://github.com/ldtteam/minecolonies/issues/9511
