### ISSUE TITLE
is have mod limit experience drop from mob or just bug in game? 

### ISSUE THREAD

**Issue by banzpopto** [LunaPixelStudios/Prominence#237]
### Describe the Bug

i just doubt about experience drop from mob when i build mob farm to farm xp. (enderman farm)
i have golden hook and enchantment soul siphon and devourer (mc dungeons weapons)
from i test all mob i kill. it just drop xp around 3 (without golden hook and enchant)
but when i equip golden hook is drop xp increase to 7 (without enchant)
and when get enchantment soul siphon or devourer is still around 7 per kill
and look like experience orb just missing when mob stuck and get kill or experience orb to much and then it missing
if i kill i just 1 mob is always drop but why when mob get stuck at one block from farm why experience so less is should be
 

### Crash Report or Log

dasd

### Operating System

window11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

1.3.6hf

### Optifine

I used Optifine

### Other Mods

Max Enchant X
clumps
darkloot
darkmining

**Comment by nvb-uy** [comment]
Yes, farms are nerfed with time. This is done to prevent abuse from players and stay with the balance. A good method is farming in the prison dimension.
