### ISSUE TITLE
When opening backpack it gives fiery plate

### ISSUE THREAD

**Issue by Dryst4** [LunaPixelStudios/Prominence#239]
### Describe the Bug

Every time I open my backpack it creates a new fiery plate from Expert Armor in the bottom right slot.

### Reproduction Steps

1. Create backpack
2.Open backpack
3.Take out fiery plate
4. repeat 2-3
...

### Screenshots and Videos

![Prominence I  FABRIC  10_19_2023 6_39_02 AM](https://github.com/LunaPixelStudios/Prominence/assets/98194386/1f1b3e22-b02c-44b3-99c8-edb9b2297dea)

### Operating System

Windows 11

### Minecraft Version

Prominence I 1.19.2

### Modloader

Fabric

### Modpack Version

v2.2.0

### Optifine

I used Optifine

**Comment by BlubbPaule** [comment]
+1 this is also true for the Wireless and normal crafting terminal of AE2. Completely gamebreaking, players are having thousands of fiery ingots on the server now.

**Comment by lukaskabc** [comment]
also its created in Applied Energistics 2 terminal (crafting) and you can take stacks from there

**Comment by lukaskabc** [comment]
also there are similar issues with another receipts without inputs - like 1337Fleece from Bewitchment Plus (appearing in ME pattern encoding terminal)
