### ISSUE TITLE
Skulk Snapper Client-Crash

### ISSUE THREAD

**Issue by doomrider023** [LunaPixelStudios/Prominence#24]
### Describe the Bug

I was in the deep-dark and got bit by a skulk-snapper, it instantly proceeded to lag out and crash my client. I also noticed snappers reproducing/spawning at an exponential rate.

### Reproduction Steps

1. Go to the Deeper Dark?
2. Find a Skulk-Snapper
3. I was holding/trying to tame them with enchanted netherite chestplates
4. Get bit by one
5. Crash

### Crash Report or Log

https://mclo.gs/2pHfbkN

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence [FABRIC] v1.6

### Optifine

No

**Comment by nvb-uy** [comment]
Report in the Deeper and Darker issue tracker
