### ISSUE TITLE
Uncrafting table breaks progression completely.

### ISSUE THREAD

**Issue by BlubbPaule** [LunaPixelStudios/Prominence#240]
### Describe the Bug

The uncrafting table allows you to uncraft anything with a REI recipe back to its base components while choosing to which components you want to reset to - Saplings can be uncrafted into dirt and uu matter, Plantballs crafted from leaves can be uncrafted into spectrum color tree saplings instead, skipping the entire progression. This works with tons of items.

### Reproduction Steps

1.Start new game
2. Go to twilight forest
3. Acquire maze map focus from labyrinth
4. Craft anything back into whatever you want.

### Operating System

Windows 11

### Minecraft Version

Prominence I 1.19.2

### Modloader

Fabric

### Modpack Version

2.2.0 (Works on any)

### Optifine

No

### Other Mods

Presence Footsteps.

**Comment by nvb-uy** [comment]
Uncrafting is disabled
