### ISSUE TITLE
Bedrock Items can not be reforged.

### ISSUE THREAD

**Issue by BlubbPaule** [LunaPixelStudios/Prominence#241]
### Describe the Bug

They have no reforge material, making your first craft a gamble. If you craft yourself a common bedrock sword you got cheated out of the weapon you painfully crafted. 

Right now i can circumvent this by un-and recrafting it in the uncrafting table (which is most likely a bug).

### Reproduction Steps

1. Craft Bedrock Item
2. Look at modifier
3. Not able to be recrafted in anvil

### Operating System

Windows 11

### Minecraft Version

Prominence I 1.19.2

### Modloader

Fabric

### Modpack Version

2.2.0

### Optifine

No

### Other Mods

Presence Footsteps.

**Comment by nvb-uy** [comment]
It is not reforgable
