### ISSUE TITLE
Ad Astra Steel Block doesn't turn into Ad Astra Steel

### ISSUE THREAD

**Issue by TheFlyingDookey** [LunaPixelStudios/Prominence#245]
### Describe the Bug

Ad Astra Steel Block doesn't turn into Ad Astra Steel Ingot through crafting or other means. There is a mod incompatibility between Tech Reborn 2 and Ad Astra that prevents the Block form to turn into Ingot for Ad Astra. It inverts to Tech Reborn 2 Steel Ingot which is really bad for the Ad Astra questline. Ad Astra steel doesn't even show up in REI, but it's still needed to have the Ad Astra version of the ingot to continue the Ad Astra questline. 

### Reproduction Steps

1. Put Ad Astra Steel Block in crafting menu to convert to ingot
2. Retrieve Tech Reborn 2 Steel Ingot instead.
3.
REI:
1: Look up @Ad_Astra "steel ingot"
2: Doesn't exist.

### Operating System

Windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.3.5

### Optifine

No

### Other Mods

Might've used Optifine, not sure, check both versions (with or without OptiFine) just in case

**Comment by illustris** [comment]
Still broken on version 2.3.0 (Fabric)
