### ISSUE TITLE
Choice Reward. In Tech Reborn Quest tree still issue after upgrade

### ISSUE THREAD

**Issue by WiseSoul881** [LunaPixelStudios/Prominence#246]
### Describe the Bug

I've found 4 achievements that give "Choice Reward"

1. Overclocker Upgrade
2. Muffler Upgrade
3. Energy Storage Upgrade
4. Compressor
When I click to claim reward it brings up window with Header "Choice Reward" but box is blank (nothing to pick)

Same as issue #164 which was closed saying fix in next upgrade.  I upgraded and still issue

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Capture](https://github.com/LunaPixelStudios/Prominence/assets/137639135/58e467b8-52c8-43b5-b4ec-1705ee11cebc)
![Capture1](https://github.com/LunaPixelStudios/Prominence/assets/137639135/c36bc35d-8e18-43fa-a73d-5ca12f52ad67)
![Capture2](https://github.com/LunaPixelStudios/Prominence/assets/137639135/74489ff2-3888-43a4-84e8-458abdd6299a)

### Operating System

Windows 10

### Minecraft Version

Prominence I 1.19.2

### Modloader

Fabric

### Modpack Version

Prominence I [FABRIC]-v2.2.0

### Optifine

No

**Comment by nvb-uy** [comment]
duplicated of #164
