### ISSUE TITLE
Crash Exit Code 6

### ISSUE THREAD

**Issue by josefan1** [LunaPixelStudios/Prominence#248]
### Describe the Bug

Whenever I try to play, the game would crash and show this. Tried multiple things such as reducing graphics, redownloaded the modpack multiple times, restarting and even updating my software.

### Reproduction Steps

1. Open curseforge
2. Press Play on Prominence II
3. On Minecraft Launcher, Launch Prominence II
4. Play single player
5. Crash
...

### Screenshots and Videos

<img width="551" alt="Screenshot 2023-10-21 at 17 45 16" src="https://github.com/LunaPixelStudios/Prominence/assets/148624409/05c8ba81-c506-4b0a-a373-62a731153702">

### Crash Report or Log

# # A fatal error has been detected by the Java Runtime Environment: # #  SIGSEGV (0xb) at pc=0x00000001ee5a557c, pid=5661, tid=259 # # JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS) # Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64) # Problematic frame: # C  [libGLProgrammability.dylib+0x8257c]  glpLLVMGetFunctionGlobalVariableUse+0x74 # # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again # # If you would like to submit a bug report, please visit: #   https://aka.ms/minecraftjavacrashes # The crash happened outside the Java Virtual Machine in native code. # See problematic frame for where to report the bug. #  ---------------  S U M M A R Y ------------  Command Line: -Djava.library.path=/Users/josefan/Documents/curseforge/minecraft/Install/bin/915cada934864c4e1cd13fb0c377fe3d34b381e2 -Djna.tmpdir=/Users/josefan/Documents/curseforge/minecraft/Install/bin/915cada934864c4e1cd13fb0c377fe3d34b381e2 -Dorg.lwjgl.system.SharedLibraryExtractPath=/Users/josefan/Documents/curseforge/minecraft/Install/bin/915cada934864c4e1cd13fb0c377fe3d34b381e2 -Dio.netty.native.workdir=/Users/josefan/Documents/curseforge/minecraft/Install/bin/915cada934864c4e1cd13fb0c377fe3d34b381e2 -Dminecraft.launcher.brand=minecraft-launcher -Dminecraft.launcher.version=2.11.24 -Djava.net.preferIPv6Addresses=system -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,JarJarFileSystems,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,forge-47.1.3.jar,forge-47.1.3 -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar -DlibraryDirectory=/Users/josefan/Documents/curseforge/minecraft/Install/libraries --module-path=/Users/josefan/Documents/curseforge/minecraft/Install/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:/Users/josefan/Documents/curseforge/minecraft/Install/libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar:/Users/josefan/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:/Users/josefan/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:/Users/josefan/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:/Users/josefan/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:/Users/josefan/Documents/curseforge/minecraft/Install/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:/Users/josefan/Documents/curseforge/minecraft/Install/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar --add-modules=ALL-MODULE-PATH --add-opens=java.base/java.util.jar=cpw.mods.securejarhandler --add-opens=java.base/java.lang.invoke=cpw.mods.securejarhandler --add-exports=java.base/sun.security.util=cpw.mods.securejarhandler --add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming -Xmx2752m -Xms256m -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -Dlog4j.configurationFile=/Users/josefan/Documents/curseforge/minecraft/Install/assets/log_configs/client-1.12.xml cpw.mods.bootstraplauncher.BootstrapLauncher --username Josefun --version forge-47.1.3 --gameDir /Users/josefan/Documents/curseforge/minecraft/Instances/Prominence II [FORGE] --assetsDir /Users/josefan/Documents/curseforge/minecraft/Install/assets --assetIndex 5 --uuid 36e6cd213f014828a5ebc3669d5eb77f --clientId NTE4MjkyMEM1QTdENEYyNTk5RUFEMzNEQTBENTIwNDE= --xuid 2535409433347991 --userType msa --versionType release --width 1024 --height 768 --quickPlayPath /Users/josefan/Documents/curseforge/minecraft/Install/quickPlay/java/1697888606514.json --launchTarget forgeclient --fml.forgeVersion 47.1.3 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412  Host: "Mac14,7" arm64, 8 cores, 8G, Darwin 23.0.0, macOS 14.0 (23A344) Time: Sat Oct 21 18:44:14 2023 WIB elapsed time: 47.610903 seconds (0d 0h 0m 47s)  ---------------  T H R E A D  ---------------  Current thread (0x000000013702fe00):  JavaThread "Render thread" [_thread_in_native, id=259, stack(0x000000016ad60000,0x000000016b55c000)]  Stack: [0x000000016ad60000,0x000000016b55c000],  sp=0x000000016b552730,  free space=8137k Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code) C  [libGLProgrammability.dylib+0x8257c]  glpLLVMGetFunctionGlobalVariableUse+0x74 C  [libGLProgrammability.dylib+0x82794]  glpLLVMGetFunctionGlobalVariableUse+0x28c C  [libGLProgrammability.dylib+0x82794]  glpLLVMGetFunctionGlobalVariableUse+0x28c C  [libGLProgrammability.dylib+0x82794]  glpLLVMGetFunctionGlobalVariableUse+0x28c C  [libGLProgrammability.dylib+0x82794]  glpLLVMGetFunctionGlobalVariableUse+0x28c C  [libGLProgrammability.dylib+0x82794]  glpLLVMGetFunctionGlobalVariableUse+0x28c C  [libGLProgrammability.dylib+0x82794]  glpLLVMGetFunctionGlobalVariableUse+0x28c C  [libGLProgrammability.dylib+0x82794]  glpLLVMGetFunctionGlobalVariableUse+0x28c C  [libGLProgrammability.dylib+0x80fd8]  glpLLVMCGFindSamplersAndBuffers+0x4a0 C  [libGLProgrammability.dylib+0x7fe48]  glpLLVMCGTopLevel+0x588 C  [libGLProgrammability.dylib+0xa7814]  glpLinkProgram+0x2708 C  [libGLProgrammability.dylib+0xc16bc]  ShLink+0xd0 C  [GLEngine+0xfeb4c]  gleLinkProgram+0x468 C  [GLEngine+0x7801c]  glLinkProgramARB_Exec+0xb4 C  0xcc62800115cf98ac j  org.lwjgl.opengl.GL20.glLinkProgram(I)V+1 org.lwjgl.opengl@3.3.1+7 j  com.mojang.blaze3d.platform.GlStateManager.glLinkProgram(I)V+4 minecraft@1.20.1 j  com.mojang.blaze3d.shaders.ProgramManager.m_166623_(Lcom/mojang/blaze3d/shaders/Shader;)V+15 minecraft@1.20.1 j  net.minecraft.client.renderer.ShaderInstance.<init>(Lnet/minecraft/server/packs/resources/ResourceProvider;Lnet/minecraft/resources/ResourceLocation;Lcom/mojang/blaze3d/vertex/VertexFormat;)V+599 minecraft@1.20.1 j  com.telepathicgrunt.the_bumblezone.forge.BumblezoneForgeClient.lambda$onRegisterShaders$6(Lnet/minecraftforge/client/event/RegisterShadersEvent;Lnet/minecraft/resources/ResourceLocation;Lcom/mojang/blaze3d/vertex/VertexFormat;Ljava/util/function/Consumer;)V+12 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.forge.BumblezoneForgeClient$$Lambda$38253+0x00000008041c3250.register(Lnet/minecraft/resources/ResourceLocation;Lcom/mojang/blaze3d/vertex/VertexFormat;Ljava/util/function/Consumer;)V+7 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.events.client.RegisterShaderEvent.register(Lnet/minecraft/resources/ResourceLocation;Lcom/mojang/blaze3d/vertex/VertexFormat;Ljava/util/function/Consumer;)V+7 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.client.BumblezoneClient.registerShaders(Lcom/telepathicgrunt/the_bumblezone/events/client/RegisterShaderEvent;)V+21 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.client.BumblezoneClient$$Lambda$10270+0x00000008016e0498.accept(Ljava/lang/Object;)V+4 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.events.base.EventHandler.invoke(Ljava/lang/Object;)V+31 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.forge.BumblezoneForgeClient.onRegisterShaders(Lnet/minecraftforge/client/event/RegisterShadersEvent;)V+16 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.forge.BumblezoneForgeClient$$Lambda$10346+0x0000000801706dd8.accept(Ljava/lang/Object;)V+4 the_bumblezone@7.0.7+1.20.1-forge J 41125 c2 net.minecraftforge.eventbus.EventBus$$Lambda$5258+0x000000080104b290.invoke(Lnet/minecraftforge/eventbus/api/Event;)V net.minecraftforge.eventbus (21 bytes) @ 0x0000000117565ed0 [0x0000000117565e40+0x0000000000000090] J 26705 c2 net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(Lnet/minecraftforge/eventbus/api/Event;)V javafmllanguage@1.20.1-47.1.3 (94 bytes) @ 0x0000000116c6d624 [0x0000000116c6d280+0x00000000000003a4] J 26727 c2 net.minecraftforge.fml.ModLoader$$Lambda$24169+0x0000000801a1f4b0.accept(Ljava/lang/Object;)V fmlcore@1.20.1-47.1.3 (12 bytes) @ 0x0000000116c9de2c [0x0000000116c9ddc0+0x000000000000006c] J 11147 c2 java.lang.Iterable.forEach(Ljava/util/function/Consumer;)V java.base@17.0.8 (39 bytes) @ 0x000000011643d600 [0x000000011643d300+0x0000000000000300] J 41264 c1 net.minecraftforge.fml.ModLoader.postEvent(Lnet/minecraftforge/eventbus/api/Event;)V fmlcore@1.20.1-47.1.3 (39 bytes) @ 0x000000010f8d3c44 [0x000000010f8d3480+0x00000000000007c4] j  net.minecraft.client.renderer.GameRenderer.m_172767_(Lnet/minecraft/server/packs/resources/ResourceProvider;)V+1791 minecraft@1.20.1 j  net.minecraft.client.renderer.GameRenderer$1.m_5787_(Lnet/minecraft/client/renderer/GameRenderer$ResourceCache;Lnet/minecraft/server/packs/resources/ResourceManager;Lnet/minecraft/util/profiling/ProfilerFiller;)V+5 minecraft@1.20.1 j  net.minecraft.client.renderer.GameRenderer$1.m_5787_(Ljava/lang/Object;Lnet/minecraft/server/packs/resources/ResourceManager;Lnet/minecraft/util/profiling/ProfilerFiller;)V+7 minecraft@1.20.1 j  net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(Lnet/minecraft/server/packs/resources/ResourceManager;Lnet/minecraft/util/profiling/ProfilerFiller;Ljava/lang/Object;)V+20 minecraft@1.20.1 j  net.minecraft.server.packs.resources.SimplePreparableReloadListener$$Lambda$32403+0x0000000803990af8.accept(Ljava/lang/Object;)V+13 minecraft@1.20.1 j  java.util.concurrent.CompletableFuture$UniAccept.tryFire(I)Ljava/util/concurrent/CompletableFuture;+105 java.base@17.0.8 j  java.util.concurrent.CompletableFuture$Completion.run()V+2 java.base@17.0.8 j  net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(Ljava/lang/Runnable;)V+1 minecraft@1.20.1 j  net.minecraft.server.packs.resources.SimpleReloadInstance$$Lambda$32660+0x00000008039dfb58.run()V+8 minecraft@1.20.1 J 39247 c1 net.minecraft.util.thread.BlockableEventLoop.m_6367_(Ljava/lang/Runnable;)V minecraft@1.20.1 (29 bytes) @ 0x00000001103179d0 [0x0000000110317940+0x0000000000000090] j  net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(Ljava/lang/Runnable;)V+12 minecraft@1.20.1 J 36157 c1 net.minecraft.util.thread.BlockableEventLoop.m_7245_()Z minecraft@1.20.1 (54 bytes) @ 0x00000001103d3190 [0x00000001103d3000+0x0000000000000190] J 39111 c1 net.minecraft.client.Minecraft.m_91383_(Z)V minecraft@1.20.1 (1179 bytes) @ 0x000000010f024b78 [0x000000010f024740+0x0000000000000438] j  net.minecraft.client.Minecraft.m_91374_()V+128 minecraft@1.20.1 j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+1572 minecraft@1.20.1 v  ~StubRoutines::call_stub V  [libjvm.dylib+0x4749b8]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*)+0x394 V  [libjvm.dylib+0x83c194]  invoke(InstanceKlass*, methodHandle const&, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, JavaThread*)+0x8f4 V  [libjvm.dylib+0x83b840]  Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, JavaThread*)+0x160 V  [libjvm.dylib+0x52fad4]  JVM_InvokeMethod+0x370 j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@17.0.8 j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+133 java.base@17.0.8 j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@17.0.8 j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@17.0.8 j  net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/ModuleLayer;)V+39 fmlloader@1.20.1-47.1.3 j  net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService([Ljava/lang/String;Ljava/lang/ModuleLayer;)V+5 fmlloader@1.20.1-47.1.3 j  net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0([Ljava/lang/String;Ljava/lang/ModuleLayer;)V+3 fmlloader@1.20.1-47.1.3 j  net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler$$Lambda$1197+0x0000000800613710.run()V+12 fmlloader@1.20.1-47.1.3 j  cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch([Ljava/lang/String;Ljava/lang/ModuleLayer;)V+11 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.LaunchServiceHandler.launch(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/ModuleLayer;Lcpw/mods/modlauncher/TransformingClassLoader;Lcpw/mods/modlauncher/LaunchPluginHandler;)V+58 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.LaunchServiceHandler.launch(Lcpw/mods/modlauncher/ArgumentHandler;Ljava/lang/ModuleLayer;Lcpw/mods/modlauncher/TransformingClassLoader;Lcpw/mods/modlauncher/LaunchPluginHandler;)V+21 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.Launcher.run([Ljava/lang/String;)V+307 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.Launcher.main([Ljava/lang/String;)V+78 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.BootstrapLaunchConsumer.accept([Ljava/lang/String;)V+1 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(Ljava/lang/Object;)V+5 cpw.mods.modlauncher@10.0.9 j  cpw.mods.bootstraplauncher.BootstrapLauncher.main([Ljava/lang/String;)V+515 cpw.mods.bootstraplauncher@1.1.2 v  ~StubRoutines::call_stub V  [libjvm.dylib+0x4749b8]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*)+0x394 V  [libjvm.dylib+0x4d95c4]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, JavaThread*)+0x12c V  [libjvm.dylib+0x4dcbe4]  jni_CallStaticVoidMethod+0x130 C  [libjli.dylib+0x54b8]  JavaMain+0x9d8 C  [libjli.dylib+0x7a88]  __JVMInit_block_invoke+0x50 C  [Foundation+0x3e970]  __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__+0x18 C  [Foundation+0x3e830]  -[NSBlockOperation main]+0x68 C  [Foundation+0x3e7c0]  __NSOPERATION_IS_INVOKING_MAIN__+0x10 C  [Foundation+0x3db68]  -[NSOperation start]+0x288 C  [Foundation+0x78fe8]  __NSThreadPerformPerform+0x108 C  [CoreFoundation+0x7dd28]  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__+0x1c C  [CoreFoundation+0x7dcbc]  __CFRunLoopDoSource0+0xb0 C  [CoreFoundation+0x7da2c]  __CFRunLoopDoSources0+0xf4 C  [CoreFoundation+0x7c61c]  __CFRunLoopRun+0x33c C  [CoreFoundation+0x7bc2c]  CFRunLoopRunSpecific+0x260 C  [libjli.dylib+0x711c]  CreateExecutionEnvironment+0x190 C  [libjli.dylib+0x34c8]  JLI_Launch+0x4bc C  [java+0x3bac]  main+0x198 C  [dyld+0x6058]  start+0x8b0  Java frames: (J=compiled Java code, j=interpreted, Vv=VM code) j  org.lwjgl.opengl.GL20C.glLinkProgram(I)V+0 org.lwjgl.opengl@3.3.1+7 j  org.lwjgl.opengl.GL20.glLinkProgram(I)V+1 org.lwjgl.opengl@3.3.1+7 j  com.mojang.blaze3d.platform.GlStateManager.glLinkProgram(I)V+4 minecraft@1.20.1 j  com.mojang.blaze3d.shaders.ProgramManager.m_166623_(Lcom/mojang/blaze3d/shaders/Shader;)V+15 minecraft@1.20.1 j  net.minecraft.client.renderer.ShaderInstance.<init>(Lnet/minecraft/server/packs/resources/ResourceProvider;Lnet/minecraft/resources/ResourceLocation;Lcom/mojang/blaze3d/vertex/VertexFormat;)V+599 minecraft@1.20.1 j  com.telepathicgrunt.the_bumblezone.forge.BumblezoneForgeClient.lambda$onRegisterShaders$6(Lnet/minecraftforge/client/event/RegisterShadersEvent;Lnet/minecraft/resources/ResourceLocation;Lcom/mojang/blaze3d/vertex/VertexFormat;Ljava/util/function/Consumer;)V+12 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.forge.BumblezoneForgeClient$$Lambda$38253+0x00000008041c3250.register(Lnet/minecraft/resources/ResourceLocation;Lcom/mojang/blaze3d/vertex/VertexFormat;Ljava/util/function/Consumer;)V+7 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.events.client.RegisterShaderEvent.register(Lnet/minecraft/resources/ResourceLocation;Lcom/mojang/blaze3d/vertex/VertexFormat;Ljava/util/function/Consumer;)V+7 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.client.BumblezoneClient.registerShaders(Lcom/telepathicgrunt/the_bumblezone/events/client/RegisterShaderEvent;)V+21 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.client.BumblezoneClient$$Lambda$10270+0x00000008016e0498.accept(Ljava/lang/Object;)V+4 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.events.base.EventHandler.invoke(Ljava/lang/Object;)V+31 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.forge.BumblezoneForgeClient.onRegisterShaders(Lnet/minecraftforge/client/event/RegisterShadersEvent;)V+16 the_bumblezone@7.0.7+1.20.1-forge j  com.telepathicgrunt.the_bumblezone.forge.BumblezoneForgeClient$$Lambda$10346+0x0000000801706dd8.accept(Ljava/lang/Object;)V+4 the_bumblezone@7.0.7+1.20.1-forge J 41125 c2 net.minecraftforge.eventbus.EventBus$$Lambda$5258+0x000000080104b290.invoke(Lnet/minecraftforge/eventbus/api/Event;)V net.minecraftforge.eventbus (21 bytes) @ 0x0000000117565ed0 [0x0000000117565e40+0x0000000000000090] J 26705 c2 net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(Lnet/minecraftforge/eventbus/api/Event;)V javafmllanguage@1.20.1-47.1.3 (94 bytes) @ 0x0000000116c6d624 [0x0000000116c6d280+0x00000000000003a4] J 26727 c2 net.minecraftforge.fml.ModLoader$$Lambda$24169+0x0000000801a1f4b0.accept(Ljava/lang/Object;)V fmlcore@1.20.1-47.1.3 (12 bytes) @ 0x0000000116c9de2c [0x0000000116c9ddc0+0x000000000000006c] J 11147 c2 java.lang.Iterable.forEach(Ljava/util/function/Consumer;)V java.base@17.0.8 (39 bytes) @ 0x000000011643d600 [0x000000011643d300+0x0000000000000300] J 41264 c1 net.minecraftforge.fml.ModLoader.postEvent(Lnet/minecraftforge/eventbus/api/Event;)V fmlcore@1.20.1-47.1.3 (39 bytes) @ 0x000000010f8d3c44 [0x000000010f8d3480+0x00000000000007c4] j  net.minecraft.client.renderer.GameRenderer.m_172767_(Lnet/minecraft/server/packs/resources/ResourceProvider;)V+1791 minecraft@1.20.1 j  net.minecraft.client.renderer.GameRenderer$1.m_5787_(Lnet/minecraft/client/renderer/GameRenderer$ResourceCache;Lnet/minecraft/server/packs/resources/ResourceManager;Lnet/minecraft/util/profiling/ProfilerFiller;)V+5 minecraft@1.20.1 j  net.minecraft.client.renderer.GameRenderer$1.m_5787_(Ljava/lang/Object;Lnet/minecraft/server/packs/resources/ResourceManager;Lnet/minecraft/util/profiling/ProfilerFiller;)V+7 minecraft@1.20.1 j  net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(Lnet/minecraft/server/packs/resources/ResourceManager;Lnet/minecraft/util/profiling/ProfilerFiller;Ljava/lang/Object;)V+20 minecraft@1.20.1 j  net.minecraft.server.packs.resources.SimplePreparableReloadListener$$Lambda$32403+0x0000000803990af8.accept(Ljava/lang/Object;)V+13 minecraft@1.20.1 j  java.util.concurrent.CompletableFuture$UniAccept.tryFire(I)Ljava/util/concurrent/CompletableFuture;+105 java.base@17.0.8 j  java.util.concurrent.CompletableFuture$Completion.run()V+2 java.base@17.0.8 j  net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(Ljava/lang/Runnable;)V+1 minecraft@1.20.1 j  net.minecraft.server.packs.resources.SimpleReloadInstance$$Lambda$32660+0x00000008039dfb58.run()V+8 minecraft@1.20.1 J 39247 c1 net.minecraft.util.thread.BlockableEventLoop.m_6367_(Ljava/lang/Runnable;)V minecraft@1.20.1 (29 bytes) @ 0x00000001103179d0 [0x0000000110317940+0x0000000000000090] j  net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(Ljava/lang/Runnable;)V+12 minecraft@1.20.1 J 36157 c1 net.minecraft.util.thread.BlockableEventLoop.m_7245_()Z minecraft@1.20.1 (54 bytes) @ 0x00000001103d3190 [0x00000001103d3000+0x0000000000000190] J 39111 c1 net.minecraft.client.Minecraft.m_91383_(Z)V minecraft@1.20.1 (1179 bytes) @ 0x000000010f024b78 [0x000000010f024740+0x0000000000000438] j  net.minecraft.client.Minecraft.m_91374_()V+128 minecraft@1.20.1 j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+1572 minecraft@1.20.1 v  ~StubRoutines::call_stub j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@17.0.8 j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+133 java.base@17.0.8 j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@17.0.8 j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@17.0.8 j  net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/ModuleLayer;)V+39 fmlloader@1.20.1-47.1.3 j  net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService([Ljava/lang/String;Ljava/lang/ModuleLayer;)V+5 fmlloader@1.20.1-47.1.3 j  net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0([Ljava/lang/String;Ljava/lang/ModuleLayer;)V+3 fmlloader@1.20.1-47.1.3 j  net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler$$Lambda$1197+0x0000000800613710.run()V+12 fmlloader@1.20.1-47.1.3 j  cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch([Ljava/lang/String;Ljava/lang/ModuleLayer;)V+11 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.LaunchServiceHandler.launch(Ljava/lang/String;[Ljava/lang/String;Ljava/lang/ModuleLayer;Lcpw/mods/modlauncher/TransformingClassLoader;Lcpw/mods/modlauncher/LaunchPluginHandler;)V+58 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.LaunchServiceHandler.launch(Lcpw/mods/modlauncher/ArgumentHandler;Ljava/lang/ModuleLayer;Lcpw/mods/modlauncher/TransformingClassLoader;Lcpw/mods/modlauncher/LaunchPluginHandler;)V+21 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.Launcher.run([Ljava/lang/String;)V+307 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.Launcher.main([Ljava/lang/String;)V+78 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.BootstrapLaunchConsumer.accept([Ljava/lang/String;)V+1 cpw.mods.modlauncher@10.0.9 j  cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(Ljava/lang/Object;)V+5 cpw.mods.modlauncher@10.0.9 j  cpw.mods.bootstraplauncher.BootstrapLauncher.main([Ljava/lang/String;)V+515 cpw.mods.bootstraplauncher@1.1.2 v  ~StubRoutines::call_stub  siginfo: si_signo: 11 (SIGSEGV), si_code: 2 (SEGV_ACCERR), si_addr: 0x0000000000000000

### Operating System

MacBook Pro, Apple M2 (Sonoma 14.0)

### Minecraft Version

Prominence I 1.19.2

### Modloader

Forge

### Modpack Version

v1.3.6

### Optifine

I do not use Optifine

### Other Mods

None

**Comment by TelepathicGrunt** [comment]
Update Bumblezone to v7.0.23. i fixed mac crashes a while ago
