### ISSUE TITLE
acquire quantum sword

### ISSUE THREAD

**Issue by g-youdong** [LunaPixelStudios/Prominence#249]
"I'm unable to obtain the quantum sword in the game. I've tried using commands, but it disappears as soon as I get it. What configuration should I use to successfully obtain the quantum sword?"

**Comment by g-youdong** [comment]
prominence II version：v1.3.6
game version：1.20.1

**Comment by nvb-uy** [comment]
item obliterator

**Comment by g-youdong** [comment]
> item obliterator

what's meaning?
