### ISSUE TITLE
Start LAN is missing

### ISSUE THREAD

**Issue by alexandersokol** [LunaPixelStudios/Prominence#25]
### Describe the Bug

Hello!
"Start for LAN" Menu entry is missing for the single player main menu.
Is there any config file to fix this?

### Reproduction Steps

1.
2.
3.
...

### Operating System

Win10, Win11, MacOS13

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence [FABRIC] v1.6

### Optifine

No

**Comment by nvb-uy** [comment]
Not a bug, LAN is incompatible.
