### ISSUE TITLE
Game Crashing all of a sudden

### ISSUE THREAD

**Issue by lkjvc** [LunaPixelStudios/Prominence#262]
### Describe the Bug

I've been playing the modpack for days now. It has never crashed since the beginning. After exploring some deep dark dungeons and caves, finding a dragon and taming it underground, I wanted to resurface and continue doing something else. But ever since then, it crashes in a couple of minutes of me loading the world.

### Reproduction Steps

Explained in the description.

### Crash Report or Log

https://pastebin.com/cPazwQRx

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

1.3.6hf initially, but then I updated to 1.4.0 to see if the bug is fixed but no luck

### Optifine

I used Optifine

**Comment by TigerWalts** [comment]
Looks like this is a bug in Nether Depths Update - Fixed in 3.1.1
- https://github.com/Scouter456/Nether_Depths_Upgrade/issues/26

**Comment by lkjvc** [comment]
Solved by updating Nether Depths mod. Thanks to TigerWalts and Tamz (on discord)
