### ISSUE TITLE
Game crashes on world start

### ISSUE THREAD

**Issue by TomasCdVGuerra** [LunaPixelStudios/Prominence#265]
### Describe the Bug

When i attempt to start the world the game crashes back to launcher

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.pl/view/482267b5

### Operating System

MacOS 14.0(23A344)

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.3.1

### Optifine

No

**Comment by nvb-uy** [comment]
update to java 21 or remove the xaero's minimap mod
