### ISSUE TITLE
Game Crash when using Spell Book

### ISSUE THREAD

**Issue by kmarshall102** [LunaPixelStudios/Prominence#267]
### Describe the Bug

I recently crafted the novice spell book, along side another friend. When we both went to form a spell, it immediately would crash us.

### Reproduction Steps

1. Open spell book
2. Click on any of the forms
... then game will crash.

### Crash Report or Log

Error: java.lang.ClassCastException: null

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Forge

### Modpack Version

ars nouveau

### Optifine

I used Optifine

**Comment by kmarshall102** [comment]
Also another crash via same item is when I have book in hand and click on the scribes table

**Comment by NickSProud** [comment]
Same problem. If I give myself a new spellbook I can open it but I cannot click any glyph wihtout crashing.

**Comment by NickSProud** [comment]
Log: https://mclo.gs/EoJz5ES Crash Report: https://mclo.gs/3CLhWCs

**Comment by Ch1ckenLover21** [comment]
Found a fix, message me on discord jujujollofrice

**Comment by w3ricardo** [comment]
Same problem here, my log:
https://gist.github.com/w3ricardo/968232541cc9e6fda338fa91c66bfc69

**Comment by MaxillS** [comment]
Can you post the fix here? Having same issue.

**Comment by Ch1ckenLover21** [comment]
Basically, u have to update the ars mod to the most recent version, then in the configs in the common section there is a config called gui transparency that is defaulted to on, u turn that off and it should solve the problem

**Comment by nvb-uy** [comment]
Fixed in latest
