### ISSUE TITLE
requirements for reforging the sword on a stick

### ISSUE THREAD

**Issue by h-kie** [LunaPixelStudios/Prominence#270]
### Describe the Bug

when trying to reforge the sword on a stick, it shows the requirements to be an extremely long list of what seems to be random items and blocks.

### Reproduction Steps

1.get a random sword on a stick (the unique weapon from the mod 'Simply Swords'
2.get an anvil and try and reforge it
3.thats it
...

### Screenshots and Videos

![Screenshot 2023-10-28 195307](https://github.com/LunaPixelStudios/Prominence/assets/149261158/4b4317ac-013e-480c-a22a-f99c280b17d1)

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.4.0hf

### Optifine

No

### Other Mods

no extra mods added

**Comment by nvb-uy** [comment]
it's not a random list of blocks, it's all the blocks permitted to reforge, because it's a stick, and sticks are made out of planks.
