### ISSUE TITLE
copper block is uncraftable

### ISSUE THREAD

**Issue by qiyoo8** [LunaPixelStudios/Prominence#272]
### Describe the Bug

The 3x3 copper recipe that should make the copper block makes the cut copper block. Because of this, there is no way to craft the copper block without the uncrafting table from tf.
a suggestion on the lunapixel discord that also touched on this and included some config stuff that i dont understand: https://discord.com/channels/790272037578473512/875960331145461780/1143912480305860620

### Reproduction Steps

1.try to make vanilla copper block in a 3x3 crafting table

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/149278042/6414b005-3d12-4a3f-9ec2-bcc80e4a5e4c)

### Operating System

Windows 10

### Minecraft Version

Prominence I 1.19.2

### Modloader

Fabric

### Modpack Version

v2.2

### Optifine

No

**Comment by nvb-uy** [comment]
fixed by latest
