### ISSUE TITLE
Dissapearing items

### ISSUE THREAD

**Issue by SubTitanium** [LunaPixelStudios/Prominence#274]
### Describe the Bug

There's a bug with Feral Claw i believe where it dissapears when you take it into your inventory from chests. Also, when you move items with shift click from your inventory to travelers backpack they dissapear, they are there but they're in some slots to the left which can only be seen when hovering over the backpack while it's in the inventory and pressing CTRL.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.4.0hf

### Optifine

No

**Comment by SubTitanium** [comment]
Found a fix for the Travelers backpack. The slots that were missing were tool slots and couldn't be seen because of the Mandala's GUI resource pack that was for an older version. Disable this resource pack for Traveler's backpack to display properly. As for the Digging Claws (not Feral Claw) i still haven't found them.

**Comment by Shadow7Striker** [comment]
Feral Claws are blacklisted by the mod "item Obliteration" so when you move it to your inventory it will delete it

**Comment by SubTitanium** [comment]
Ahhh thank you for that, closing this.
