### ISSUE TITLE
Server closed upon entering the nether.

### ISSUE THREAD

**Issue by Fisque51** [LunaPixelStudios/Prominence#28]
### Describe the Bug

The server was running perfectly fine until I entered the nether for the first time, the server shut down with two different logs.

### Reproduction Steps

1. Make the portal
2. Enter in the portal
3. Surprise !
...

### Crash Report or Log

https://gist.github.com/Fisque51/041e24e539e06e746542abfd26ca2a87

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.6

### Optifine

No

**Comment by nvb-uy** [comment]
Update to 1.6.1
