### ISSUE TITLE
Server cannot start

### ISSUE THREAD

**Issue by ImJacko1510** [LunaPixelStudios/Prominence#282]
### Describe the Bug

I installed a Mohist 1.20.1 server to put the modpack, but when i start it, it trows an crash and then stops the server.

https://mclo.gs/jp7A70B

### Reproduction Steps

1.  Insert the mods (Without starting the server before)
2. Install Mohist (And start the server with the mods)
3.
...

### Crash Report or Log

https://mclo.gs/jp7A70B

### Operating System

Linux

### Minecraft Version

Prominence II 1.20.1

### Modloader

Forge

### Modpack Version

Latest (V.1.3.7)

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
We don't offer support to modified versions of the modpack, modify it at your own risk.
