### ISSUE TITLE
Puffish Skill Tree

### ISSUE THREAD

**Issue by SmitchyB** [LunaPixelStudios/Prominence#284]
### Describe the Bug

Puffish skill tree does not open regardless of what keybinding is set. 

### Reproduction Steps

1. Try to press k(other keybindings assigned)
2. Change keybinding to a key thats not assigned to something
3. Skill tree still doesnt open. Start of the game and the main feature i wanted is broken:/
...

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Forge

### Modpack Version

Prominence II Forge V1.3.7

### Optifine

No

### Other Mods

A few aether adons, few ad astra adons, changed better combat and combat roll to epic fight. switched HT Falling trees to regular falling trees.
[Smitchy's Place V2-v1.3.7.zip](https://github.com/LunaPixelStudios/Prominence/files/13245801/Smitchy.s.Place.V2-v1.3.7.zip)

**Comment by nvb-uy** [comment]
Don't motify the modpack. The skill tree is desgined around better combat and its compatible mods
