### ISSUE TITLE
can't translate quests

### ISSUE THREAD

**Issue by sturtle333** [LunaPixelStudios/Prominence#285]
### Describe the Bug

sorry, it's not a bug.

I'm willing to translate quests but don't have some base modes.

KubeJS
ftb x-compat (Modes required to use ftbquest and kubeJS together)

If there is no problem adding the above two modes, I would like to add them.

Please reply.
Thank you very much for providing a good mod pack.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

1.4.1hf

### Optifine

No

**Comment by nvb-uy** [comment]
I'm not planning on adding translated quests. The modpack is in english and it's too much work to translate to other languages.
