### ISSUE TITLE
Quest book bag

### ISSUE THREAD

**Issue by Perdynebychii** [LunaPixelStudios/Prominence#288]
### Describe the Bug

Mod: Ad Astra. Cannot complete the quest "Making Iron Sheets" becouse that hasn't a task to gather

### Reproduction Steps

Add the task to quest "Making Iron Sheets" in Quest book; Ad Astra Mod

### Screenshots and Videos

![изображение_2023-11-04_041404481](https://github.com/LunaPixelStudios/Prominence/assets/149847667/727d1914-d33c-498b-ba80-53cf5a13cb4c)

### Operating System

Windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.0.0

### Optifine

No

**Comment by nvb-uy** [comment]
you're using the first version ever of the modpack lol
