### ISSUE TITLE
Crash when smashing Spectrum gems under an anvil.

### ISSUE THREAD

**Issue by SpLayzDK** [LunaPixelStudios/Prominence#29]
### Describe the Bug

When you throw an anvil on some Topaz Shards, the game crashes. 

### Reproduction Steps

1. Create a new world, and get some Topaz Shards.
2. Drop the Topaz Shards on the ground.
3. Place an anvil over them.
4. The game should crash.

### Screenshots and Videos

https://github.com/LunaPixelStudios/Prominence/assets/92643775/82c3a2b4-1ddd-4916-885e-57c93be589ee

### Crash Report or Log

https://pastebin.com/C0WR3yT1

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

The latest one at this moment, v1.6

### Optifine

No

### Other Mods

No other mods, no.

**Comment by nvb-uy** [comment]
fixed in 1.6.1
