### ISSUE TITLE
Modpack version of Create causes memory leak that crashes server.

### ISSUE THREAD

**Issue by viniciusbrit** [LunaPixelStudios/Prominence#291]
Please update Create to the latest version, the version available in the modpack has a memory leak that slowly consumes all the server ram until it crashes. I'm hosting a server with 10Gb of ram and if I don't restart it every 12 hours it will just implode.
This issue has been fixed as of CreateEnchantmentIndustry version 1.27.f.
Please update.

**Comment by nvb-uy** [comment]
Fixed in latest
