### ISSUE TITLE
Prominence 2 fabric

### ISSUE THREAD

**Issue by Entityyyyy** [LunaPixelStudios/Prominence#294]
### Describe the Bug

blank enchantment books when looting chests on my server. anyway to fix this?

### Reproduction Steps

1.loot a chest
2.if it has an enchanted book hover over it
3. its blank
...

### Operating System

windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.4.1hf

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
Fixed in 1.5.0
