### ISSUE TITLE
Unable to Craft anything

### ISSUE THREAD

**Issue by TimeStop12** [LunaPixelStudios/Prominence#296]
### Describe the Bug

As the title suggests i am unable to craft anything. The whole crafting UI as well is very laggy and picking up a item to place into the crafting grid makes the game hang for a second or two. 

### Reproduction Steps

1. Open either the Inv or use a crafting table
2. place an item in the crafting grid.
3. Nothing happens
...

### Screenshots and Videos

![2023-11-06_17 06 45](https://github.com/LunaPixelStudios/Prominence/assets/2638355/4453e897-2e89-4a13-bb77-5a317dce73e0)

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.4.2

### Optifine

No

**Comment by KrakenBinary** [comment]
Same issue here

**Comment by bendgk** [comment]
I have this issue too

**Comment by TimeStop12** [comment]
Latest hotfix fixed this issue
