### ISSUE TITLE
neruina mod 昨晚开始将我从单人游戏踢出到服务器列表

### ISSUE THREAD

**Issue by cloverplayer233** [LunaPixelStudios/Prominence#298]
### Describe the Bug

我昨晚吃个饭的功夫，neruina开始将我在没操控几分钟的情况下把我从单人游戏踢到服务器列表，此前我已经游玩了三四天都没有这种情况

### Reproduction Steps

1.进入单人存档
2.游玩没有几分钟黑屏
3.跳转到neruina踢人
...

### Screenshots and Videos

![QQ图片20231108005049](https://github.com/LunaPixelStudios/Prominence/assets/150174511/93be5e0e-e129-44b8-8809-dfb64a353eab)

### Crash Report or Log

没有报告直接回到主界面

### Operating System

win 10

### Minecraft Version

Prominence I 1.19.2

### Modloader

Forge

### Modpack Version

不懂

### Optifine

No

**Comment by nvb-uy** [comment]
English only, send logs.
