### ISSUE TITLE
Suggestion: Add Iris & Oculus Flywheel Compat mod

### ISSUE THREAD

**Issue by ganderhero** [LunaPixelStudios/Prominence#3]
### Describe the Bug

This mod allows Create's optimization engine Flywheel to work with Iris shaders, namely Complementary Reimagined works the best from the 4 built-in shaders on this list.
It currently has problems with iris shaders version 1.6.2 but not with 1.6.1 nor 1.6.0.
The mod also doesn't work well with the other 3 shaders as Rethinking voxels and the other two aren't 'patched' to work with this mod yet, but with Complementary Reimagined you can expect a huge performance increase and stability when using Create's contraptions.
https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.5

### Optifine

I used Optifine

### Other Mods

Iris & Oculus Flywheel Compat (https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)

**Comment by chorbintime** [comment]
This has been forwarded to Elocin for consideration.

This modpack is for Fabric, not Forge.

Optifine is also incompatible with all of our modpacks, and there is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Optifine is also not a Fabric mod.

**Comment by ganderhero** [comment]
Hi so as you might have not noticed github for some reason automatically put this issue into Forge and Optifine, which is not the case, the mod I linked is a Fabric mod that makes both Flywheel and Iris Shaders more compatible with eachother instead of iris shaders turning off flywheel's optimizations.

**Comment by ganderhero** [comment]
Also, I never ticked the options 'I used optifine' and neither Forge as the modloader, this automation system completely mistook my whole issue
