### ISSUE TITLE
Can't craft traveler's backpacks with the Comforts sleeping bag

### ISSUE THREAD

**Issue by piousdeer** [LunaPixelStudios/Prominence#30]
### Describe the Bug

The default sleeping bag that appears when you lay down 3 wool in a crafting table is from the Comforts mod, while the sleeping bag required to craft a backpack is from the Traveler's Backpack mod. Also, the Open to LAN button is hidden for some reason, so I had to edit the configs and restart the game to enable cheats and get the right item.

### Operating System

NixOS

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.6.1hf

### Optifine

No

**Comment by nvb-uy** [comment]
Use Polymorph to craft the correct one

**Comment by se7enek** [comment]
https://i.imgur.com/N56lujs.gif
if it only wasnt broken

**Comment by nvb-uy** [comment]
You can use polymorph to switch the crafting of the sleeping bag, this is getting fixed in 1.3.5

>
