### ISSUE TITLE
Game crash when atack mob

### ISSUE THREAD

**Issue by icecoldbadj** [LunaPixelStudios/Prominence#302]
### Describe the Bug

the game crashes when I try to hit a mob, with the code "The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'double net.puffish.skillsmod.access.EntityAttributeInstanceAccess.computeIncreasedValueForInitial(double)"

### Reproduction Steps

1.open game.
2.atack mob
3.
...

### Crash Report or Log

The game crashed whilst unexpected error Error: java.lang.NoSuchMethodError: 'double net.puffish.skillsmod.access.EntityAttributeInstanceAccess.computeIncreasedValueForInitial(double)

### Operating System

windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

1.5.0

### Optifine

I used Optifine

**Comment by Kehhhcaso** [comment]
Having the same issue

**Comment by Kehhhcaso** [comment]
Hotfix resolved the issue
