### ISSUE TITLE
Weapon attacking animation not displaying when equipping invisibility cloak from Aether mod

### ISSUE THREAD

**Issue by AlisonHuang777** [LunaPixelStudios/Prominence#304]
### Describe the Bug

See footage.

### Screenshots and Videos

https://github.com/LunaPixelStudios/Prominence/assets/51637996/b38edb35-f544-463d-a6e3-5f446dd1bdf7

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Forge

### Modpack Version

1.4.0

### Optifine

No

### Other Mods

Removed:
- https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

Added:
- https://www.curseforge.com/minecraft/mc-mods/framedblocks
- https://www.curseforge.com/minecraft/mc-mods/chunk-loaders
- https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib
- https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib

**Comment by nvb-uy** [comment]
report to aether's issue tracker
