### ISSUE TITLE
Stuck in the questbook

### ISSUE THREAD

**Issue by CombatCarl3** [LunaPixelStudios/Prominence#31]
### Describe the Bug

pressing escape exits to the inventory from the questbook, pressing escape or e to exit the inventory goes back to the questbook. repeat. not 100% sure if its reproduceable

### Reproduction Steps

1. look at a crafting recipe in rei
2. open questbook using in the inventory
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.6.1

### Optifine

No

**Comment by Zarvera** [comment]
Same problem, it happens uncomfortably often. 
And by that i mean it makes the pack barely playable.
Basically you just get stuck in a loop between quests screen and REI, trying to exit quest screen via "e" or ESC or any other way just  puts you back into the REI recipes and exiting REI recipes\closing inventory puts you back to the quest menu. There's no escape besides Alt+F4, shutting minecraft down via task manager or any similar hard quit.

**Comment by nvb-uy** [comment]
Update to latest version
