### ISSUE TITLE
Item Obliterator causing null value crash when crafting trimmed armour

### ISSUE THREAD

**Issue by EsanVoid** [LunaPixelStudios/Prominence#310]
### Describe the Bug

while playing multiplayer with some friends every player crashed while trying to add a trim to their armour, I looked into the issue and tested adding a trim in singleplayer and it still crashed.

I did further testing by removing one mod related to the trims or smithing table at a time but the issue persisted even with a purely vanilla table and trim, the going over the crash log again more carefully I noticed the two vanilla calls to the smithing trim recipe and armour trim recipe followed by "at MC//net.minecraft.recipe.RecipeManager.mdeb0d59$item_obliterator$lambda$item_obliterator$getRecipesFor$1$5" the $ signs tipped me off as they matche the $$0 in the crash error and the moment i ripped it out of the mod list trimming armour worked perfectly again

### Reproduction Steps

1. open any smithing table in either multiplayer or singleplayer
2. try to fill all crafting slots with a trim, armour and trimming material
3. game will crash to launcher when you try to add either the last item (no matter which) and give an error along the lines of _java.lang.NullPointerException: Cannot invoke "net.minecraft.registry.DynamicRegistryManager.get(net.minecraft.registry.RegistryKey)" because "$$0" is null_
...

### Crash Report or Log

https://pastebin.com/jJUmVAvP

### Operating System

windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.5.0chorb

### Optifine

No

**Comment by ElliotTheClown** [comment]
having the same problem

**Comment by ElliotTheClown** [comment]
> ### Describe the Bug
> while playing multiplayer with some friends every player crashed while trying to add a trim to their armour, I looked into the issue and tested adding a trim in singleplayer and it still crashed.
> 
> I did further testing by removing one mod related to the trims or smithing table at a time but the issue persisted even with a purely vanilla table and trim, the going over the crash log again more carefully I noticed the two vanilla calls to the smithing trim recipe and armour trim recipe followed by "at MC//net.minecraft.recipe.RecipeManager.mdeb0d59$item_obliterator$lambda$item_obliterator$getRecipesFor$1$5" the $ signs tipped me off as they matche the $$0 in the crash error and the moment i ripped it out of the mod list trimming armour worked perfectly again
> 
> ### Reproduction Steps
> 1. open any smithing table in either multiplayer or singleplayer
> 2. try to fill all crafting slots with a trim, armour and trimming material
> 3. game will crash to launcher when you try to add either the last item (no matter which) and give an error along the lines of _java.lang.NullPointerException: Cannot invoke "net.minecraft.registry.DynamicRegistryManager.get(net.minecraft.registry.RegistryKey)" because "$$0" is null_
>    ...
> 
> ### Screenshots and Videos
> _No response_
> 
> ### Crash Report or Log
> https://pastebin.com/jJUmVAvP
> 
> ### Operating System
> windows 10
> 
> ### Minecraft Version
> Prominence II 1.20.1
> 
> ### Modloader
> Fabric
> 
> ### Modpack Version
> v1.5.0chorb
> 
> ### Optifine
> No
> 
> ### Other Mods
> _No response_

help me lol

**Comment by EsanVoid** [comment]
> > ### Describe the Bug
> > while playing multiplayer with some friends every player crashed while trying to add a trim to their armour, I looked into the issue and tested adding a trim in singleplayer and it still crashed.
> > I did further testing by removing one mod related to the trims or smithing table at a time but the issue persisted even with a purely vanilla table and trim, the going over the crash log again more carefully I noticed the two vanilla calls to the smithing trim recipe and armour trim recipe followed by "at MC//net.minecraft.recipe.RecipeManager.mdeb0d59$item_obliterator$lambda$item_obliterator$getRecipesFor$1$5" the $ signs tipped me off as they matche the $$0 in the crash error and the moment i ripped it out of the mod list trimming armour worked perfectly again
> > ### Reproduction Steps
> > 
> > 1. open any smithing table in either multiplayer or singleplayer
> > 2. try to fill all crafting slots with a trim, armour and trimming material
> > 3. game will crash to launcher when you try to add either the last item (no matter which) and give an error along the lines of _java.lang.NullPointerException: Cannot invoke "net.minecraft.registry.DynamicRegistryManager.get(net.minecraft.registry.RegistryKey)" because "$$0" is null_
> >    ...
> > 
> > ### Screenshots and Videos
> > _No response_
> > ### Crash Report or Log
> > https://pastebin.com/jJUmVAvP
> > ### Operating System
> > windows 10
> > ### Minecraft Version
> > Prominence II 1.20.1
> > ### Modloader
> > Fabric
> > ### Modpack Version
> > v1.5.0chorb
> > ### Optifine
> > No
> > ### Other Mods
> > _No response_
> 
> help me lol

I mentioned it in the report description but just click the three dots and hit open folder on the mod instance you installed in curseforge and go into the mods folder and delete item obliterator from the list of mods, simple as that, there's no official fix for it atm outside of that, but this temp fix works for existing saves with no issue

**Comment by nvb-uy** [comment]
Fixed by 1.5.1
