### ISSUE TITLE
game crashes when trimming items 

### ISSUE THREAD

**Issue by noisuhfjshksaj** [LunaPixelStudios/Prominence#311]
### Describe the Bug

when i try to use trims on my armor the game crashes

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

release

### Optifine

No

### Other Mods

EI

**Comment by HeadHunterShiv** [comment]
Upload crash/latest log for better assistance also has the pack been modified in any way?

**Comment by nvb-uy** [comment]
Fixed by 1.5.1
