### ISSUE TITLE
Alloy forgery deletes items

### ISSUE THREAD

**Issue by ant040** [LunaPixelStudios/Prominence#312]
### Describe the Bug

Using the alloy forges from the alloy forgery mod randomly deletes items put into it, but only when those items are correct ingredients for a recipe.

### Reproduction Steps

1. Build and alloy forge, any tier.
2. Place in ingredients for any compatible recipe, you may need to try two or three different ones because sometimes (but uncommonly) it will function as intended.
3. Watch as the items vanish into thin air.

### Screenshots and Videos

https://github.com/LunaPixelStudios/Prominence/assets/150963025/08a0b875-12cb-45f5-9436-08a5e278c315

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.5.0chorb

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed in 1.6.0, wait until the update is out
