### ISSUE TITLE
Screen on the right won't go away

### ISSUE THREAD

**Issue by Foxy1887** [LunaPixelStudios/Prominence#315]
### Describe the Bug

I don't know why, but I have constantly a this screen on the right with "Sorcerer's Metal 100%" and "Printed Silicon 100%":
![image](https://github.com/LunaPixelStudios/Prominence/assets/151207259/beb10c2b-08b2-4894-a9ba-7d1076e32161)

I don't know where it came from and only I have this window on my screen, none of my 3 friends I play with. I have reinstalled the game 3 times and it still won't go away. I searched online for this problem, but didn't find anything. The only settings I changed were 3 hotkeys, so I don't know where this annoying window comes from. 

### Reproduction Steps

1.I have no idea. The window on the right was there out of nowhere
2.
3.
...

### Screenshots and Videos

![Unbenannt1](https://github.com/LunaPixelStudios/Prominence/assets/151207259/5261470a-ee06-49a1-9f1c-cca4f302765d)

### Operating System

Windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.6.1

### Optifine

No

**Comment by nvb-uy** [comment]
you pinned a quest
