### ISSUE TITLE
My Backpack containing valuable (Diamonds, Netherite, Mending Enchantments, etc.) disappeared on the official SMP server.

### ISSUE THREAD

**Issue by CashewTaku** [LunaPixelStudios/Prominence#316]
### Describe the Bug

I went onto the title screen for Prominence II and when I went to multiplayer it told me I had to update the version to 1.6.1. I finished updating and reloaded the launcher and went onto the server. Everything was fine until I tried to open my backpack I had equipped. At first I thought the update had changed my key binds so I shifted it back, but when I used the key to open my backpack it didn't work. I checked the backpack trinket slot and my backpack wasn't there. It just disappeared. All my other things were still in my inventory and chests. But the only thing with actual valuables disappeared

### Reproduction Steps

I don't know exactly what I did before the problem.

### Crash Report or Log

N/A game did not crash.

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.6.1

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
This is not the place to report a bug from a server. This is for the modpack. Contact the server's staff.
