### ISSUE TITLE
Latest update (v1.6.0) breaks alt + F3

### ISSUE THREAD

**Issue by AlisonHuang777** [LunaPixelStudios/Prominence#317]
### Describe the Bug

When you press alt + F3, nothing shows up.
It should shows the frame time graph, which is useful for checking if the game is lagging or not.

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Forge

### Modpack Version

1.6.0

### Optifine

No

### Other Mods

Removed:
- https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

Added:
- https://www.curseforge.com/minecraft/mc-mods/framedblocks
- https://www.curseforge.com/minecraft/mc-mods/chunk-loaders
- https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib
- https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib

**Comment by nvb-uy** [comment]
will look into it, use spark in the meantime, it's way better.

**Comment by AlisonHuang777** [comment]
Is this fixed?
