### ISSUE TITLE
Dark Enchanter from Dark Enchanting Not giving discount

### ISSUE THREAD

**Issue by OPDragongod** [LunaPixelStudios/Prominence#319]
### Describe the Bug

So its seems that in v1.5.0 dark enchant is working find especially giving the exp discount but in the latest version (v1.6.1) dark enchant is not giving the exp discount what so ever. 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/151396198/a3413839-83e3-441b-beff-67c79fc7e11b)
![image](https://github.com/LunaPixelStudios/Prominence/assets/151396198/97df1767-5f6d-4881-a425-ea1bc48b76b1)

First one is v1.6.0, second one is 1.5.0

### Operating System

Windows 10 Home

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v1.6.0

### Optifine

No

**Comment by nvb-uy** [comment]
Intended
