### ISSUE TITLE
GUI Size 3 button in wrong location

### ISSUE THREAD

**Issue by Savior10K** [LunaPixelStudios/Prominence#32]
### Describe the Bug

as above

### Reproduction Steps

1.set GUI to size 3
2.join game
3.pause
...

### Screenshots and Videos

<img width="960" alt="2023-05-30 00_52_48-Prominence  FABRIC  1 19 2" src="https://github.com/LunaPixelStudios/Prominence/assets/112022902/fa6591bd-096b-4860-8f2c-1dc1a6f60879">

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence 1.6.1hf

### Optifine

No

**Comment by nvb-uy** [comment]
Known issue, will be fixed in the next update

**Comment by Savior10K** [comment]
broken again lmao
