### ISSUE TITLE
Enchantment issue

### ISSUE THREAD

**Issue by pepitoooooooo** [LunaPixelStudios/Prominence#321]
### Describe the Bug

When u enchant anything on the enchantment table (vanilla one) and then u disenchant on the dark enchanter (dark enchanting mod) u receive EXPONENCIAL level from the disenchant

U spend 3 level enchanting at level 30 and u gain like 60 lvl  on the disenchant

is my server (i am hosting playing on localhost)

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

first one ![image](https://github.com/LunaPixelStudios/Prominence/assets/151418649/53620f79-611e-41df-9cee-8c5673478ab2)

second one 
![image](https://github.com/LunaPixelStudios/Prominence/assets/151418649/6f87428f-a10f-4a5b-955a-4912a785d33a)

third one 
![image](https://github.com/LunaPixelStudios/Prominence/assets/151418649/6e78e8cb-9d29-421c-9f8a-513bf08a94a3)

fourth one 
![image](https://github.com/LunaPixelStudios/Prominence/assets/151418649/e9961a80-8a74-4236-b95f-8256f5013101)

final 
![image](https://github.com/LunaPixelStudios/Prominence/assets/151418649/5c33f0cc-ad19-4f9d-b8b6-64f854e68b2e)

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

1.6.1

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed by v2.0.0 (comes out tomorrow)
