### ISSUE TITLE
Character Model Showing in Crosshair

### ISSUE THREAD

**Issue by Mikachuy** [LunaPixelStudios/Prominence#327]
### Describe the Bug

It seems my character model (Outfit) is displaying on the crosshair, without the ability to toggle off. This is specific to outfits - this includes both normal armor as well as Cosmetic armor - it seems as though the character itself is invisible, so if I take off all my clothes - it appears nothing is showing. 
![2023-11-21_13 02 15](https://github.com/LunaPixelStudios/Prominence/assets/76406201/f4b3ca1a-99d6-4921-be80-ae579b2dfe5a)
![2023-11-21_13 08 53](https://github.com/LunaPixelStudios/Prominence/assets/76406201/0c9ed608-1ffb-4c3e-940b-deb5e7e6e05a)
![2023-11-21_13 08 58](https://github.com/LunaPixelStudios/Prominence/assets/76406201/dbf8f4a4-c401-45f5-93b1-eb8cc825c1a1)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

Prominence I 1.19.2

### Modloader

Forge

### Modpack Version

v1.5.0

### Optifine

No

**Comment by nvb-uy** [comment]
1. This is not Prominence I
2. You have an outdated version, update the modpack
