### ISSUE TITLE
Tree Chop's Buggy

### ISSUE THREAD

**Issue by Fyrend08** [LunaPixelStudios/Prominence#328]
### Describe the Bug

Since the update to version 1.6 i can't use this mod. I only can take one block after one

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Forge

### Modpack Version

1.6

### Optifine

No

**Comment by nvb-uy** [comment]
cant repro
