### ISSUE TITLE
Me Crafting Interface Crash

### ISSUE THREAD

**Issue by sniperbuddy500** [LunaPixelStudios/Prominence#34]
### Describe the Bug

clicking terminal style button 4 times in the Me crafting interface from Applied energetics 2 crashes the game everytime for me

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/7aPvw8ui

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.16.1hf

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
We don't support OptiFine.

Crash is related to smooth swapping, remove that mod
