### ISSUE TITLE
conflicting furnace output recipe for soul sand: scoria and lost soul

### ISSUE THREAD

**Issue by Mumberthrax** [LunaPixelStudios/Prominence#341]
### Describe the Bug

the recipe to acquire lost soul item from marium's soulslike weaponry is displaced by the recipe for scoria from create. A search on the lunapixels discord shows months ago users saying scoria could be smelted for lost souls - I assume this fix was not included in the recent update where create was put back into the pack.

### Reproduction Steps

1. lookup crafting recipe for lost soul in REI (soul sand in furnace)
2. put soul sand in furnace and cook
3. put scoria into furnace and try to cook
...

### Operating System

linux

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

2.0.1

### Optifine

No

**Comment by JadenIttanenn** [comment]
I assume that you're using Modern Industrialization Steam Furnaces? Using Normal Furnaces there's a selector you can click to pick lost souls. Using Steam Furnaces you have to take a lost soul and "lock" them in using the lock button on the top right of the furnace UI

**Comment by Mumberthrax** [comment]
> I assume that you're using Modern Industrialization Steam Furnaces? Using Normal Furnaces there's a selector you can click to pick lost souls. Using Steam Furnaces you have to take a lost soul and "lock" them in using the lock button on the top right of the furnace UI

You're right. I completely missed it when i tested in a regular furnace. I put it in a tech reborn electric furnace and got scoria, then put in regular furnace and saw it produced scoria, but overlooked the output selection button it seems. Thank you.
