### ISSUE TITLE
Issues with keybinds on fabric

### ISSUE THREAD

**Issue by AroAceToast** [LunaPixelStudios/Prominence#343]
### Describe the Bug

Whenever I change the sprint keybind it has it so that I have to press ctrl and the key that i want to use. If i reset it, it will say C (ctrl) + Left control. I'm not the only person who has this issue, as #107 describes the same issue. It could be related to the mouse buttons, as we both used the front side mouse button (Mouse 5) for sprint.

### Reproduction Steps

1. Download Current version at the time of this report
2. Go to controls and try to change the sprint keybind to Mouse 5 or Mouse 4 (just incase it is an issue with the side mouse buttons)
3. If it says "C + Mouse 5/4", Reset.
...

### Screenshots and Videos

![Screenshot 2023-11-28 054128](https://github.com/LunaPixelStudios/Prominence/assets/114693438/f8e49d6e-c6ee-4c8d-9476-949286003d06)

![image](https://github.com/LunaPixelStudios/Prominence/assets/114693438/206d1314-9165-464d-95df-936b3bd60023)

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v2.0.1

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed on latest
