### ISSUE TITLE
I cannot start a Lan server.

### ISSUE THREAD

**Issue by BMREAPER** [LunaPixelStudios/Prominence#346]
### Describe the Bug

Whenever my friend and I try to play locally the person not hosting times out before they can join. We have tried on multiple other modpacks to make sure there are no issues on our end aswell. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

Prominence I 1.19.2

### Modloader

Fabric

### Modpack Version

2.0.1

### Optifine

No

**Comment by nvb-uy** [comment]
lan is unsupported, use world sharing instead, or make a local server using the serverpack
