### ISSUE TITLE
lags in opening inventory or crafting table to anyother functional block

### ISSUE THREAD

**Issue by SUPERS21** [LunaPixelStudios/Prominence#347]
### Describe the Bug

lags in opening inventory or crafting table to anyother functional block

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

lastest

### Optifine

No

**Comment by nvb-uy** [comment]
remove the model fix mod
