### ISSUE TITLE
Last update (v2.1.0) makes it impossible to connect to server (Exaroton ?)

### ISSUE THREAD

**Issue by SDK4rma** [LunaPixelStudios/Prominence#352]
### Describe the Bug

We're trying to start a server on Prominence II with friends. 
Two days ago, I successfully launched the server via Exaroton (initially on the version 2.0.1 of the modpack) and we managed to log in and play for a bit without any issue. 

Today however, we couldn't log into the server. 
We then found that Exaroton automatically updated the server version to v2.1.0, so we updated our clients too. 
We're now up to date with the server, but when we try to log in, we encounter a Javascript error, or the client just crashes. 

Looking into the console logs, the server seems to be overloaded when someone tries to connect, so it automatically disconnects the player ...

### Reproduction Steps

1. Updating server version to v2.1.0 (automatically made by Exaroton
2. Updating client version to v2.1.0
3. Trying to connect to the server

### Crash Report or Log

https://gist.github.com/SDK4rma/52c0e8538e052e5f2d70e5888611b18a

### Operating System

Windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

Prominence II v2.1.0

### Optifine

No

**Comment by nvb-uy** [comment]
2.1.1 is the latest
