### ISSUE TITLE
Create item tooltips showing extra bit of symbols for the Russian locale

### ISSUE THREAD

**Issue by murolem** [LunaPixelStudios/Prominence#374]
### Describe the Bug

For the Russian locale, Create's item tooltips show `%1$s` after `Kinetic stress capacity` (`Допустимая нагрузка` in Russian).

### Reproduction Steps

1. Add Russian as a language (followed by English).
2. Look at the item tooltip for any Create item that has `Kinetic stress capacity` in its tooltip.

### Screenshots and Videos

**In English**
![image](https://github.com/LunaPixelStudios/Prominence/assets/20380250/0003d441-61f8-499b-beae-510b5e10cd6f)

**In Russian**
![image](https://github.com/LunaPixelStudios/Prominence/assets/20380250/1519bb02-70ff-4520-9e77-a17a286fe9a6)

### Operating System

Windows 11

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v.2.2.1

### Optifine

No

**Comment by nvb-uy** [comment]
This is not the place to report it
