### ISSUE TITLE
Vein Mine 

### ISSUE THREAD

**Issue by ITAL556** [LunaPixelStudios/Prominence#38]
### Describe the Bug

Vein mine is not working. I already put a key to use it.

### Reproduction Steps

1.
2.
3.
...

### Operating System

w10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.6.1

### Optifine

No

### Other Mods

Dynamic Lights 
https://www.curseforge.com/minecraft/mc-mods/dynamic-lights

**Comment by InFuRiTy** [comment]
Have you put the enchantment on your tool first?

**Comment by nvb-uy** [comment]
You need an enchantment
