### ISSUE TITLE
Fell through world when trying to get on a mount that was on top of Prisoner's Quarters portal

### ISSUE THREAD

**Issue by mcfizzlestag** [LunaPixelStudios/Prominence#40]
### Describe the Bug

Fell through world in prisoners quarters when trying to get on a mount that was on top of Prisoner's Quarters portal.  Spawned into a black screen, ~30 seconds later, fell through world to  bottom floor.  Forced to TP via server console.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.6.1hf

### Optifine

I used Optifine

### Other Mods

Default mod back, no additions.  REI settings adjusted to reduce icon rendering causing lag whenever crafting.

**Comment by nvb-uy** [comment]
Optifine is not supported

**Comment by mcfizzlestag** [comment]
Optifine has not been installed.  Its just the default selection in the bug report for some reason and i wasn't sure if it was included.  Under other mods i explained i left everything as is w/o additions.

![image](https://github.com/LunaPixelStudios/Prominence/assets/44690968/f4fa9221-e2c2-4caf-b6c7-7c036077cab3)
