### ISSUE TITLE
Potion Charms + Potion Skill Tree

### ISSUE THREAD

**Issue by RattlyCheese4** [LunaPixelStudios/Prominence#41]
### Describe the Bug

when you go down the potion skill tree and get the skills that have % chance to make it a beneficial potion it makes the potion called superior strength(any potion) the crafting recipe wont recognize the potion as being a the right potion to craft it

### Reproduction Steps

1. Get beneficial potions strength skill
2. Brew potions and it'll have a chance of making it superior potion
3. Try and craft the charm

### Crash Report or Log

none

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.0.1

### Optifine

No

**Comment by nvb-uy** [comment]
Not on us, either report to Apotheosis or Passive Skill Tree
