### ISSUE TITLE
chest texture bugged

### ISSUE THREAD

**Issue by oink69420** [LunaPixelStudios/Prominence#414]
### Describe the Bug

chest are looking bugged

### Reproduction Steps

it happens as soon as i go to my world

### Screenshots and Videos

![Screenshot 2024-01-18 014659](https://github.com/LunaPixelStudios/Prominence/assets/156976976/510f5b9d-ee9e-4b57-ad42-5ee870afc36f)

### Operating System

windows 10

### Minecraft Version

Prominence II 1.20.1

### Modloader

Fabric

### Modpack Version

v2.5.0

### Optifine

No

**Comment by nvb-uy** [comment]
Disable flywheel backend with /flywheel backend off
