### ISSUE TITLE
Scrolling through JEI will crash your game

### ISSUE THREAD

**Issue by Vennexus** [LunaPixelStudios/Prominence#43]
### Describe the Bug

If you don't use the search bar and just use the arrow buttons, it'll crash the game.

### Reproduction Steps

1. Just scroll through JEI using the arrow buttons without using the search bar.
2. Around the 50+ mark, there'll be a crash.
3. Bug report says mimic is "null"
...

### Crash Report or Log

https://github.com/LunaPixelStudios/Prominence/files/11631093/crash-2023-06-02_09.34.08-client.txt

### Operating System

MacOS

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Prominence v1.0.1

### Optifine

No

**Comment by embeddedt** [comment]
Appears to be triggered by a Connectedness mixin.

**Comment by Micaxs** [comment]
Seems to happen when you search for "str" as well in jei.

**Comment by kittycat2002** [comment]
"@bu" also triggered it for me.

**Comment by kittycat2002** [comment]
https://github.com/Asek3/Connectedness/issues/9 seems to be related to this.

**Comment by nvb-uy** [comment]
https://github.com/Direwolf20-MC/BuildingGadgets/pull/738
