### ISSUE TITLE
Minor factual error in the AE2 questline (Fabric)

### ISSUE THREAD

**Issue by 100lewi** [LunaPixelStudios/Prominence#44]
The questline states that you need a diamond pickaxe to collect the meteors from AE2 when you only need an iron one. See images below below
![image](https://github.com/LunaPixelStudios/Prominence/assets/1654416/567f8d58-e8c2-43cd-a9ab-96dd52f8eddc)
![image](https://github.com/LunaPixelStudios/Prominence/assets/1654416/8f6305fd-1ab7-4f44-b237-d8671b591de7)

**Comment by nvb-uy** [comment]
Fixed in v2.0.0
