### ISSUE TITLE
essential mod breaking the single player or multiplayer buttons

### ISSUE THREAD

**Issue by dufuw** [LunaPixelStudios/Prominence#46]
### Describe the Bug

When i add the essential mod to play with my friends it brakes the single player and multiplayer buttons not allowing me to create a world

### Reproduction Steps

1.
2.
3.
...

### Operating System

macOS ventura 13.3.1 (a)

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.7.0

### Optifine

I used Optifine

**Comment by SirWaltray** [comment]
I have a solution. Disable fancymenu (add button to open its own menu in the settings) and all will work

**Comment by dufuw** [comment]
ok thanks i'll try that

**Comment by dufuw** [comment]
thank you it worked i couldn't disable the mod but i removed it from the modpack and now it works without needing to add a button to open its own menu in the settings.
