### ISSUE TITLE
Disappearing Some Artifacts and Tome (from RelicEx)

### ISSUE THREAD

**Issue by Ka1dz0** [LunaPixelStudios/Prominence#48]
### Describe the Bug

When trying to pick up the "Tome" as well as some artifacts, they just disappear without getting into the inventory, and do not give anything

### Operating System

Windows 8.1-10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.7.0

### Optifine

No

**Comment by InFuRiTy** [comment]
It's intended behavior. Those items are disabled from the pack devs for balance reasons. That's why they disappear on pickup.

**Comment by nvb-uy** [comment]
Not a bug, intended behavior.

**Comment by matthewd253** [comment]
Is there anyway to enable some of those items on a server, like through the config files? I understand that they are disabled for a reason but some people would like to have them enabled in there server.

**Comment by InFuRiTy** [comment]
> Is there anyway to enable some of those items on a server, like through the config files? I understand that they are disabled for a reason but some people would like to have them enabled in there server.

Apologies for the late response... im just gonna leave this here in case you haven't figured it out yet...the disabled items are in the config files of the InControl mod. Find the right config file, open it and delete the code line block of the item you want re-enabled!!
