### ISSUE TITLE
Industrial Revolution hammer consumed when crafting iron plates

### ISSUE THREAD

**Issue by 100lewi** [LunaPixelStudios/Prominence#49]
### Describe the Bug

When using the hammer from **Industrial Revolution** to craft iron plates it consumes the hammer instead of costing durability.

### Screenshots and Videos

Images of the recepies used in the gif (both are crafting **Create** plates):
![image](https://github.com/LunaPixelStudios/Prominence/assets/1654416/cbbf2cd0-5410-426e-b841-1536d1a57210)
![image](https://github.com/LunaPixelStudios/Prominence/assets/1654416/084367e0-6b5e-44e5-82c7-8b1aaf3a4f2a)

Gif showing the bug in action:
![javaw_dos9FsStMe](https://github.com/LunaPixelStudios/Prominence/assets/1654416/27ac4661-7959-4da2-b88e-a9c62c8d40ec)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.7.0

### Optifine

No

### Other Mods

No mods were added

**Comment by nvb-uy** [comment]
Not on us, it's its behavior
