### ISSUE TITLE
Can't connect to server.

### ISSUE THREAD

**Issue by RadiumRemix** [LunaPixelStudios/Prominence#5]
### Describe the Bug

I simply launch my server with the mods from the pack and attempt to join with the mods installed on my client.

For some reason it's not working... but I can join the official server just fine. I can even play on singleplayer just fine.

### Reproduction Steps

1. Started Server
2. Started my client
3. Attempted to Join server
4. Error when attempting to join server

### Screenshots and Videos

![Screenshot (7)](https://github.com/LunaPixelStudios/Prominence/assets/93145687/a8a44441-c66a-4df2-af5c-a7ed4a3cd1b4)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence

### Optifine

No

**Comment by smsteel** [comment]
How we actually supposed to start the server with this modpack? Didn't find any guide or what server to actually use. The same error occurs if i just copy papermc to mod folder and run it.

**Comment by smsteel** [comment]
@RadiumRemix well i figured it out. You have to download server pack and launch start script from there. 
This button in forge app downloads it:
![image](https://github.com/LunaPixelStudios/Prominence/assets/2188716/cdd5a6dd-f59a-4d58-a252-6986278a0242)

Then use `start.ps1` from PowerShell if you're on Windows or `start.sh` if you're on Linux

**Comment by chorbintime** [comment]
This has nothing to do with the modpack nor the server.

You just don't have the same modpack installed as the server. Please make sure you're on the same modpack version as the server.
