### ISSUE TITLE
Latest Server Pack Incorrectly Marked

### ISSUE THREAD

**Issue by NotGeri** [LunaPixelStudios/Prominence#50]
### Describe the Bug

From what I can tell, the latest version of the modpack's server pack needs to be correctly marked as such, making it very difficult to update programmatically: https://www.curseforge.com/minecraft/modpacks/prominence-fabric/files/4563694

This is the setting I believe causes it:
![image](https://github.com/LunaPixelStudios/Prominence/assets/46295973/a67f8214-3812-477e-9fbf-dd9d81964ee3)

### Reproduction Steps

1. Send a `GET` request to `https://api.curseforge.com/v1/mods/835917/files/` and see that the latest server pack does not show up as the `serverPackFileId` property.
2. Go to the UI and open the file manually: https://www.curseforge.com/minecraft/modpacks/prominence-fabric/files/4563694
3. Copy its ID and `GET` request that: `https://api.curseforge.com/v1/mods/835917/files/4563694` and see that it shows up in the API fine.

### Operating System

Irrelevant

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.7.0

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed
