### ISSUE TITLE
Using "Xpetrified Orb"crashes client.

### ISSUE THREAD

**Issue by Micaxs** [LunaPixelStudios/Prominence#51]
### Describe the Bug

When using the item "Xpetrified Orb" the client crashes.

### Reproduction Steps

1. Get XPetrified Orb
2. Use.
3. Crash

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/14205312/3bea9e7f-b780-40fd-b1d4-f2f981d5278d)

### Operating System

Windows

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.0.1

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed in latest
