### ISSUE TITLE
Crash report Prominence

### ISSUE THREAD

**Issue by BurritoKing01** [LunaPixelStudios/Prominence#53]
### Describe the Bug

Estaba jugando tranquilamente en mi mundo del modpack Prominence cuando al estar en el nether se me crashea el minecraft, por lo que decido cerrarlo. Al intentar abrirlo de nuevo, se me vuelve a crashear poniendo "server closed".
Además, al actualizar a 1.7 no me sale la opción de jugar a mi mundo.
El código de error es: -1
Error: java.lang.StackOverflowError: Ticking entity

### Reproduction Steps

1. Estaba en el nether
2. Me dispara un ghast
3. Le devuelvo la bola de fuego con una flecha
4. Se crashea el juego
5.
...

### Screenshots and Videos

![123](https://github.com/LunaPixelStudios/Prominence/assets/135605945/d1129c47-23dd-4b21-b1f9-d0fca99866a1)

### Crash Report or Log

The game crashed whilst ticking entity Error: java.lang.StackOverflowError: Ticking entity

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.6

### Optifine

No

**Comment by InFuRiTy** [comment]
I translated your post into English to read it and i can confirm that this Nether related crash happens in our server too.
At random times a player will wander around the nether and it will trigger this ticking entity while loading chunks effectively crashing the whole server and keep crashing it immediately every time they join.
The only solution that works so far is for our admin to reset the player's position back to spawn.

**Comment by nvb-uy** [comment]
Didn't provide logs. The error is too generic and we cannot troubleshoot anything with it, please send the full crash report.

**Comment by InFuRiTy** [comment]
> Didn't provide logs. The error is too generic and we cannot troubleshoot anything with it, please send the full crash report.

I can ask our admin to send me the log files from the server, will that help with both our cases?

**Comment by nvb-uy** [comment]
Yes
