### ISSUE TITLE
Find me mod not working!

### ISSUE THREAD

**Issue by InFuRiTy** [LunaPixelStudios/Prominence#54]
### Describe the Bug

Whatever keybind i assign to it, the mod refuses to show me available items in inventories that are close by.

When i press the key, i'd expect the "poof" effect in surrounding inventories but nothing happens!

I tried it without my custom additions, still doesn't work!

### Reproduction Steps

1. Load into a world/server
2. Hover over an item you're sure to have in other inventories.
3. Press the key to find items
4. Nothing happens

### Operating System

Windows 10 Pro

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence v1.7

### Optifine

No

**Comment by Nightstlzzz** [comment]
As far as I can see, this mod is not in the server package. On the client side it is (in singleplayer it works). "FindMe" only works when the mod is on the client side and on the server.

**Comment by nvb-uy** [comment]
SPC issue, the mod isn't present in the serverpack, will be fixed for the next updates
