### ISSUE TITLE
Can't feed chicken with seeds / Feeding Trough doesn't work on ducks (wheat)

### ISSUE THREAD

**Issue by Nightstlzzz** [LunaPixelStudios/Prominence#55]
### Describe the Bug

After spawning normal Chicken from minecraft or modded chicken i can't feed then with seeds. Although Feeding Trough from Animal Feeding Trough doesn't work for chickens/ducks (Ducks eats wheat).

### Reproduction Steps

1. Put Feeding Trough on the ground close to chickens or ducks.
2. Put seeds or wheat (depends on bird)
3. Animals didn't eat from the trough
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v1.7.0

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
Not enough info / Optifine is not supported.
