### ISSUE TITLE
update server from v1.6.0 to v1.7.0

### ISSUE THREAD

**Issue by Nightstlzzz** [LunaPixelStudios/Prominence#57]
### Describe the Bug

After updating the server and uploading the old world from the previous update, I get a string of this error popping up every 5 minutes or so. Probably not everything was removed from the Professions modification, or I messed something up :D

### Reproduction Steps

1. Download new server package
2. Copy old world to new folder server and change name in server-properties to old world name
3. Run start.ps1
...

### Screenshots and Videos

![bug](https://github.com/LunaPixelStudios/Prominence/assets/124571719/47f0367f-63c4-47b4-a88a-41e32fb3f3c3)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v1.7.0

### Optifine

No

**Comment by nvb-uy** [comment]
Known issue, will be fixed in next update
