### ISSUE TITLE
FancyMenu singleplayer/multiplayer buttons disabled if certain mods installed, why?

### ISSUE THREAD

**Issue by jpruitt2297** [LunaPixelStudios/Prominence#58]
Upon adding Essential to Prominence so I may play with friends without a server, I noticed the main menu singleplayer and multiplayer buttons disappeared. Looking into the config, I saw these buttons were disabled if Essential, Optifine, or TLSkinCape were detected. Removing any lines that detected for Essential so that I may properly use said mod, the buttons returned and modpack worked as intended with added mod.

Is there an actual reason behind disabling the main menu buttons if these mods are detected? As I see no reason to this, although I have not done full testing of every detail to the pack.

![image](https://github.com/LunaPixelStudios/Prominence/assets/49281856/abfecc3f-d9bb-4153-8e60-d66e448818c4)
![image](https://github.com/LunaPixelStudios/Prominence/assets/49281856/b03ca7bf-fd5a-4929-9ea3-57b206512d84)

**Comment by jpruitt2297** [comment]
Extra details if needed:
MC version: 1.19.2
Modloader: Fabric 0.14.19
Modpack version:  1.7.0

**Comment by SeanWalker37** [comment]
I ran into the same exact issue.. was very confused

**Comment by nvb-uy** [comment]
This is to prevent incompatible mods and pirated launchers. Not an issue.

**Comment by Quoply1** [comment]
Hey I was wondering  where you accessed the config? Me and my friend are trying to do so.

**Comment by nvb-uy** [comment]
> 

It is not supported, simply download the serverpack and start a local server

**Comment by Atomixe** [comment]
> > 
> 
> It is not supported, simply download the serverpack and start a local server

any specific reason its not supported? me and my friends cant simply "start a server" whenever we want to play using the serverpack, none of us are able to port forward + i dont believe theres anything in the pack actually preventing essential from not working.

**Comment by nvb-uy** [comment]
Some mods are incompatible with the modpack, cause issues such as world corruption. We add this to prevent players from using them and coming to the server asking for help because they lost their world.

>>>

**Comment by Atomixe** [comment]
> Some mods are incompatible with the modpack, cause issues such as world corruption. We add this to prevent players from using them and coming to the server asking for help because they lost their world.
> […](#)
> >>

i understand the world corruption part, but why not just add a disclaimer instead of outright not letting people use the mod? it seems like much more effort than its worth

**Comment by Atomixe** [comment]
> > > Some mods are incompatible with the modpack, cause issues such as world corruption. We add this to prevent players from using them and coming to the server asking for help because they lost their world.
> > 
> > 
> > > […](#)
> > 
> > 
> > > > >
> > 
> > 
> > i understand the world corruption part, but why not just add a disclaimer instead of outright not letting people use the mod? it seems like much more effort than its worth
> 
> We had a disclaimer. I invite you to go to our discord server and search the messages from people asking why their world is inaccessible or why they lost their player data.

as unfortunate as that is, it does make sense.
i do believe it should atleast be easier to disable the popup, instead of having to go through and manually change the config, but i guess if im running that risk it makes sense 🤷‍♀️

**Comment by nvb-uy** [comment]
You shouldn't even be able to disable it because it is intended. We provide the modpack as-is and we don't give support to nor guarantee that modified versions will work.
