### ISSUE TITLE
Crash pressing "s" button on the pause/main menu

### ISSUE THREAD

**Issue by Inteprise** [LunaPixelStudios/Prominence#59]
### Describe the Bug

Exactly as title says

### Reproduction Steps

1. Press the s button
2. crash
3.
...

### Crash Report or Log

https://mclo.gs/CSCtPcg

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.0.1

### Optifine

No

### Other Mods

ftb ultimine, disabled fps reducer and smooth swapping

**Comment by nvb-uy** [comment]
That button shouldn't even appear in the first place, update the modpack
