### ISSUE TITLE
Crash when Shift-clicking items from inventories. Mostly sophisticated backpack.

### ISSUE THREAD

**Issue by Goten92x** [LunaPixelStudios/Prominence#61]
### Describe the Bug

The title preety much sums it up. The bug doesn't occur when picking the same items manually from the backpack. it doesn't always happen.

### Reproduction Steps

1. Open inventory or (better) sophisticated backpack
2. Shift-click an item to move it in your inventory

### Crash Report or Log

https://pastebin.com/H7RVXB01

### Operating System

Windows 10 Enterprise

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v1.0.1

### Optifine

No

### Other Mods

 - Ars omega
- Ars elemental
- Too many glyphs
- Ars instrumentum
- Ars artifice

**Comment by tickleberrydude** [comment]
I have the exact same issue. It seems to only happen after trying to shift click something out of my backpack back into my inventory if the item is in the 4th row or below. I posted a screenshot. The dirt highlighted in blue will not crash, but the ladders and other items below ladders will cause the game to crash.

[https://pastebin.com/25L2vxjW](https://pastebin.com/25L2vxjW)

![crash report bug](https://github.com/LunaPixelStudios/Prominence/assets/10748001/9859e853-3740-41de-ac3a-745b8c6cf345)

**Comment by tickleberrydude** [comment]
A workaround is to remove the `Smooth Swapping-1.19.2-1.0.2` mod from the client side. This ended up working for me perfectly, and I can still join the same server no problem.

**Comment by tickleberrydude** [comment]
I'm pretty sure this mod expects the maximum container size to be a double chest, which is the biggest size you can get in base minecraft. So when you go above that amount, it just goes out of bounds. My guess is a static array is set in the mod somewhere, and it just goes out of bounds as per the error.
