### ISSUE TITLE
Moonlight Greatsword don't work as expected

### ISSUE THREAD

**Issue by ZirarWZ** [LunaPixelStudios/Prominence#63]
### Describe the Bug

You can't right click with the Moonlight Greatsword or the Pure Moonlight Greatsword

### Reproduction Steps

1.Get yourself a Moonlight Greatsword
2. Press mouse 2 since there is no keybind for it
3. Your sword is going to refresh but not gonna use the expected "Moonlight ability" (Moonlight beams every right click)
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.7.0

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed in latest
