### ISSUE TITLE
Incorrect information in the Powah chapter

### ISSUE THREAD

**Issue by 100lewi** [LunaPixelStudios/Prominence#65]
### Describe the Bug

The quest for the player transmitter sais "[ . . . ] allows a player to charge machinery around it [ . . . ]". This is incorrect or as what the block does is charge items in the players inventory/curio/armor slots.

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/1654416/12801bb1-6e0b-490e-b7d3-e7c70711eb04)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.7.0

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed in v2.0.0
