### ISSUE TITLE
BetterEnd anvil duplication

### ISSUE THREAD

**Issue by Epilups** [LunaPixelStudios/Prominence#66]
### Describe the Bug

When mining any of the betterend mod anvils - thalassium, terminite, aeternium, with a pickaxe that has the "Collection" enchantment, it will return 2 anvils back to your inventory. One regular, and another with "NBT tag" on it, but both still work and can be further duplicated.

### Reproduction Steps

1. Get a tool with collection enchantment
2. Get an anvil from the BetterEnd mod, such as an aeternium anvil.
3. Mine the anvil, and observe inventory to see that it has been duplicated into 2 anvils which have different item id's seemingly as they cannot be stacked on top of another.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.7

### Optifine

No

**Comment by nvb-uy** [comment]
Not on our end, will get fixed
