### ISSUE TITLE
not letting un-equip the backpacks

### ISSUE THREAD

**Issue by Princess-Yahaira** [LunaPixelStudios/Prominence#69]
### Describe the Bug

lately, i was trying to unequip the backpack and refuses to do

### Reproduction Steps

1. i got a dimaond leather from the zombie
2. i putted my stuff in the backpack
3. i equipped and now it wont let go
...

### Screenshots and Videos

![2023-06-11_12 27 23](https://github.com/LunaPixelStudios/Prominence/assets/136262846/5f30e1c6-e571-4314-b24e-813690ab0517)
![2023-06-11_12 27 28](https://github.com/LunaPixelStudios/Prominence/assets/136262846/d726e5da-8b99-4bff-a881-039bdadebfa7)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

prominence v1.7

### Optifine

No

**Comment by nvb-uy** [comment]
Open the backpack menu and click in the unequip button at the left
