### ISSUE TITLE
Crash when hoverring over item with skilltree gemsockets.

### ISSUE THREAD

**Issue by Micaxs** [LunaPixelStudios/Prominence#70]
### Describe the Bug

Client crashes when player opens up inventory.

### Reproduction Steps

1. Open inventory (might be realted to socketed weapons)
2. Crash

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/14205312/16e56222-689b-437a-b3bf-8f2f2278facd)

### Crash Report or Log

https://gist.github.com/Micaxs/3ec4602977e0a97b9749c04e1e95bc67

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Prominence [FORGE] - v1.0.2

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed for the next update
