### ISSUE TITLE
error when adding replaymod for version 1.19.2

### ISSUE THREAD

**Issue by GezaRamadhani01** [LunaPixelStudios/Prominence#72]
### Describe the Bug

 got some error while install replaymod on this modpack, while enterin the world there said "failed to connect the server"

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/96734359/408bd60a-fc33-4f3a-8a57-b99653c62fa3)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.7.0

### Optifine

No

### Other Mods

Replaymod  version 1.19.2

**Comment by nvb-uy** [comment]
Incompatible
