### ISSUE TITLE
topaz spawn not working

### ISSUE THREAD

**Issue by DrSansor** [LunaPixelStudios/Prominence#74]
### Describe the Bug

simplismente os cristais de topázio não estão aparecendo 

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.7.0

### Optifine

No

**Comment by nvb-uy** [comment]
English, please.
You can find topaz in deserts
