### ISSUE TITLE
Can't craft Cincinnasite gear

### ISSUE THREAD

**Issue by Nightstlzzz** [LunaPixelStudios/Prominence#76]
### Describe the Bug

Cincinnasite Ingot doesn't exist. Even recipies for sword etc. doesn't show anything.

### Reproduction Steps

1. Open eq
2. Try to find Cincinnasite Sword
3. Try to craft it.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/124571719/cb0d1007-8c64-4a93-8e32-ab8ae41c5215)
![image](https://github.com/LunaPixelStudios/Prominence/assets/124571719/3dfc737f-e2d4-42db-9cf4-75d4d1bf37cf)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v1.7.0

### Optifine

No

**Comment by nvb-uy** [comment]
It's not ingot-based and you have to smelt it
