### ISSUE TITLE
Backpack crash on latest update

### ISSUE THREAD

**Issue by StepOnShadows** [LunaPixelStudios/Prominence#77]
### Describe the Bug

When Shift clicking items out of a sophisticated backpack your game will crash, happened on older update, and on the latest update

(the crash logs show 3 seperate crash logs for latest update, 1 update ago, and 2 updates ago)

### Reproduction Steps

1. get sophisticated backpack
2. put item in
3. shift click item out
... crash

### Crash Report or Log

https://gist.github.com/StepOnShadows/f3f269e1983eff1e1da6e44c86056fbd

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

latest update, and the 2 prior

### Optifine

No

**Comment by nvb-uy** [comment]
Remove smooth swapping
