### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by miningbrain** [LunaPixelStudios/Prominence#78]
### Describe the Bug

If u choose to open backpack, put the items on crafting table upgrade HUD and turn on to "put directly on players inventory" (something like that) and clicks SHIFT to put in your inventory the itens the game crashes

(i am not american so thats my best try t explain what im suffering for, mb)
also i using tlauncher

### Reproduction Steps

1.open backpack
2.do a craft
3.click shift in the result
...
also needs craft upgrade

### Operating System

w11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v1.0.2

### Optifine

No

**Comment by nvb-uy** [comment]
Remove smooth swapping
