### ISSUE TITLE
Easy Dupe bug

### ISSUE THREAD

**Issue by Shortmess** [LunaPixelStudios/Prominence#79]
### Describe the Bug

I can make a copy of anything that can go into an shulker box or storage cell. This includes mana, XP inside of xp storages, relics, and any blocks/materials.

The glitch dupe item is called 
wands:magic_bag_3
wands:magic_bag_2
wands:magic_bag_1

### Reproduction Steps

1. Craft the magic tier bags
2. place anything you want to dupe into the shulker box and storage cell.
3. Place that shulker box filled with items you want to dupe inside of the magic bag.
4. Manually place empty shulkerbox or storage cells into that magic bag as much as you want.
5. Take out all the shulkerbox/ storage cells and they should all have identical inventories.

### Screenshots and Videos

https://streamable.com/4sayea

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.17

### Optifine

No

**Comment by nvb-uy** [comment]
Disabled items in latest version
