### ISSUE TITLE
Server doesnt work for version 1.8.0

### ISSUE THREAD

**Issue by ins1der833** [LunaPixelStudios/Prominence#80]
### Describe the Bug

When trying to start a server using the server pack a problem comes up say that the fabric loader is 0.14.19 and it needs to be 0.14.21

### Reproduction Steps

1.Try to start a server using the server pack on windows

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence v1.8.0

### Optifine

No

**Comment by Nightstlzzz** [comment]
Just change Modloader version i variables.txt
![modloader](https://github.com/LunaPixelStudios/Prominence/assets/124571719/859bec3b-fc72-4062-9f34-b052b3fa016b)

**Comment by mexmer** [comment]
> Just change Modloader version i variables.txt ![modloader](https://user-images.githubusercontent.com/124571719/248480512-859bec3b-fc72-4062-9f34-b052b3fa016b.PNG)
unfortunately this doesn't work, tried it, and it still downloads 1.14.19 for some reason ... deleted .fabric folder from existing install, tried it on clean folder with modified server variables

**Comment by mexmer** [comment]
FYI, this is what i get on existing instance after changing variables and deleting .fabric folder
`
Starting server...

**Minecraft version: 1.19.2
Modloader:         Fabric
Modloader version: 0.14.21**
Launcher JAR:      fabric-server-launcher.jar

Java args:         -Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true
Java path:         java
Run Command:       java -Dlog4j2.formatMsgNoLookups=true -Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar fabric-server-launcher.jar nogui
Java version:
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

**Installing Fabric Loader 0.14.19(1.19.2) on the server**
Downloading required files
`

**Comment by nvb-uy** [comment]
SPC issue not detecting the proper version, can be fixed as seen above, and will be fixed by default in the next update
