### ISSUE TITLE
Crash on new world

### ISSUE THREAD

**Issue by alexistb2904** [LunaPixelStudios/Prominence#81]
### Describe the Bug

Crash when i start a new world with Prominence II Forge or even Fabric.

### Reproduction Steps

1. Start a new world
2.
3.
...

### Crash Report or Log

https://pastebin.com/6ADZV6uN

### Operating System

Windoww 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

2

### Optifine

I used Optifine

**Comment by nvb-uy** [comment]
Use tags properly.
That isn't a crash log
