### ISSUE TITLE
Wrong server version for BCC

### ISSUE THREAD

**Issue by mexmer** [LunaPixelStudios/Prominence#84]
### Describe the Bug

when using server modpack from curseforge in bcc.config json is following entry
```
{"projectID":835917,"modpackName":"Prominence [FABRIC] 1.19.2","modpackVersion":"v1.8.0","useMetadata":false}
```
problem is that client version is 
```
{"projectID":835917,"modpackName":"Prominence I [FABRIC] 1.19.2","modpackVersion":"v1.8.0","useMetadata":false}
```
therefore client reports incompatible server version, although they should be compatible

### Reproduction Steps

1. download 1.8.0 server pack, install it, launch
2. download 1.8.0 client, install it, launch
3. go to server browser, server has X symbol and BCC reports incompatibile server version

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/5429727/a347b345-82a5-4596-9aaf-8f39cea75fbd)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.8.0

### Optifine

No

**Comment by nvb-uy** [comment]
Known issue, will be fixed in the next update
