### ISSUE TITLE
Ink Bushes in Nether don't render the block they are on

### ISSUE THREAD

**Issue by Backstabath** [LunaPixelStudios/Prominence#85]
### Describe the Bug

When looking at an Ink Bush in the Nether, the block its on is see-through, allowing you to look at everything below it.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-06-26_11 24 40](https://github.com/LunaPixelStudios/Prominence/assets/137808691/573f5276-94a2-4634-a1bd-f9112616070a)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence 1 1.8.0

### Optifine

No

**Comment by nvb-uy** [comment]
Can you try disabling dynamic resources in the modernfix-mixins config file?

**Comment by Backstabath** [comment]
I believe its disabled, but it still has the texture bug.




![2023-06-26_23 07 46](https://github.com/LunaPixelStudios/Prominence/assets/137808691/bcf5be3a-8fc7-4065-abd9-cc6d548f7f97)
![mixinperf](https://github.com/LunaPixelStudios/Prominence/assets/137808691/63507546-5971-402c-ac03-6bf8fe158f36)

**Comment by nvb-uy** [comment]
@embeddedt could this be a modernfix-caused issue?

**Comment by embeddedt** [comment]
If it happens without dynamic resources I'm skeptical as models shouldn't really be affected in that case. However it's easy enough to test without and see to be sure.

**Comment by nvb-uy** [comment]
Can't reproduce
