### ISSUE TITLE
Dupe bug with Travelers backpack mod

### ISSUE THREAD

**Issue by StevenKoska1** [LunaPixelStudios/Prominence#86]
### Describe the Bug

Found a dupe bug with the Travelers backpack mod. It only works with raw metal that can be crafted into raw metal blocks.

### Reproduction Steps

1. Craft a Block of raw iron in the Travelers backpack
2. Uncrafting the block of raw iron should give you raw iron but instead it gives you iron ore blocks, like in 1.16 version of minecraft, before the caves and cliffs update
3. Place down the iron ore blocks and use fortune enchanted pickaxe to break it and it gives you multiple raw iron. 
4. Repeat step 1 and you have infinite supply of raw iron.

### Crash Report or Log

None

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence I [FABRIC] v1.8.0

### Optifine

No

**Comment by StevenKoska1** [comment]
Edit: You can craft the iron ore blocks with raw iron blocks on any crafting table.

**Comment by nvb-uy** [comment]
Not related to backpacks, will get fixed next update
