### ISSUE TITLE
rarely getting experience when killing mobs

### ISSUE THREAD

**Issue by wizardoflife** [LunaPixelStudios/Prominence#87]
### Describe the Bug

mobs are just rarely dropping experience when I kill them

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.8.0

### Optifine

No

**Comment by wizardoflife** [comment]
it happens after i used a sword with knowledge of the ages

**Comment by lantrol** [comment]
Happened exactly the same here. I have a server set up where I play with friends. After using a sword with knowledge of ages, we stopped getting experience. Sometimes we get, but usually not. It seems to affect people who haven't touched the sword.

**Comment by nvb-uy** [comment]
If you kill too many monsters in a chunk the total experience will decay. This is made to incentive exploration more instead of making experience farms. You can disable this by going to playerex config and setting the xp negation factor to 100
