### ISSUE TITLE
Missing menu buttons

### ISSUE THREAD

**Issue by ryf21** [LunaPixelStudios/Prominence#88]
### Describe the Bug

Where did my buttons go?

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/117450234/5d8ec732-045e-47dd-be44-8a48da4d44ce)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

prominence 1 1.8.0

### Optifine

No

### Other Mods

I haven't add any extra mods

**Comment by JaggedGem** [comment]
Are you using Tlauncher?

**Comment by ryf21** [comment]
Yes I am

**Comment by ryf21** [comment]
> Are you using Tlauncher?
Yes I am

**Comment by ryf21** [comment]
> Are you using Tlauncher?

Yes I am

**Comment by nvb-uy** [comment]
We don't support piracy
