### ISSUE TITLE
Soul Sucker Boots giving +700 armor

### ISSUE THREAD

**Issue by 100lewi** [LunaPixelStudios/Prominence#89]
### Describe the Bug

See the title

Fixed in the newest version of "Nether Depths Upgrade"

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Prominence/assets/1654416/7fbe30a7-2101-4d9c-95f7-c15d14b0d637)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence 2 v0.2

### Optifine

No

**Comment by nvb-uy** [comment]
Fixed in latest version
