### ISSUE TITLE
Infinite Rocket Fuel

### ISSUE THREAD

**Issue by H0rologium** [LunaPixelStudios/Prominence#90]
### Describe the Bug

So I was playing on Prominence 1.7.0 on a server hosted remotely. I was progressing to start making rocket fuel. I wanted a storage unit to hold said rocket fuel so I crafted an Advanced Tank Unit from Tech Reborn. I understand this may be a 1.7 issue only nor am I looking for a fix ;) however I thought it might still be good to bring this up.

My (Ad Astra) Fuel Refinery was already full of rocket fuel, so I placed  the Advanced Tank directly below the Refinery. In the tank settings, I set the Configure Fluids tab to pull in to the machine. Keep in mind the Advanced Tank can hold over 516,000 MB of fluid. The tank proceeds to completely fill with rocket fuel WITHOUT draining any rocket fuel from the Refinery.

### Reproduction Steps

1. Place & power the Rocket Fuel Refinery from Ad Astra
2. Put some oil into the Refinery until its output is full of Rocket Fuel
3. Place an Advanced Tank Unit from Tech Reborn directly below the refinery (untested with other tank units)
4. In the Advanced Tank Unit UI, open the Configure Fluids tab
5. In the respective tab, Check the "Pull In" option, then close the UI entirely
6. The tank will now fill with 'infinite' fuel
7. You can use buckets to withdraw as much fuel as you want, it will continue to fill without pulling from the Refinery

### Screenshots and Videos

![2023-06-30_17 22 10](https://github.com/LunaPixelStudios/Prominence/assets/33498180/46189751-1a6d-4f3b-8549-9d92d253e0c8)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.7.0

### Optifine

No

### Other Mods

Added:

- 'Dustrial Decor
- CC:C Bridge
- Minecraft Transit Railway
- Nicer Skies
- Turtlematic
- Immersive Paintings

Disabled/Removed

- Blur
- Companion
- Simple Discord RPC

**Comment by nvb-uy** [comment]
Report to Ad Astra's devs
