### ISSUE TITLE
Prominence is not working for Meta Quest 2

### ISSUE THREAD

**Issue by Chaosminecraft** [LunaPixelStudios/Prominence#92]
### Describe the Bug

I wanted to play Prominence I Fabric on VR, and it failed to start and it shows the error "Failed to initialise stereo rendering plugin: OpenVR Installation Corrupt (101)".

### Reproduction Steps

1. Run the game with the MC launcher i get from CurseForge
2. Selecting yes when asked if wanted to turn on VR
3. Getting an Orange colour on the Prominence Window until the error message
...

### Screenshots and Videos

The orange screen before the error: https://github.com/LunaPixelStudios/Prominence/assets/48801311/72e45a9e-c142-44c1-b0a6-69710bd05732

The Error screen: https://github.com/LunaPixelStudios/Prominence/assets/48801311/9b250140-4bbf-4d6c-afc3-10b2a945d3d5

### Crash Report or Log

https://sharetext.me/o2y3gjpyf1

### Operating System

Windows 10 Pro 21H2 Build 19044.3086

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.8.0

### Optifine

No

### Other Mods

On the Fabric version there is Sodium used.

**Comment by nvb-uy** [comment]
You need to have SteamVR open before you launch the game
