### ISSUE TITLE
Breaking Claim blocks/Griefing (Immediate attention)

### ISSUE THREAD

**Issue by Shortmess** [LunaPixelStudios/Prominence#93]
### Describe the Bug

Using any of the builder's wand, you can destroy,place, replace any blocks on a person's claim without effort or warnings.

Could there be a possible config file that affects the use of using on someone's claim? The item is very useful but with the potential griefing option, it must be looked at ASAP.

### Reproduction Steps

1. Craft builder's wand
2. Use any of it's functions on someone's claim
3. Congrats, you have successfully griefed someone's base
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence V1.8.0

### Optifine

No

**Comment by nvb-uy** [comment]
It's sadly not on us, we already suggest disable it in public servers to prevent griefing
