### ISSUE TITLE
Tech Reborn block Elevator only partially works

### ISSUE THREAD

**Issue by mcfizzlestag** [LunaPixelStudios/Prominence#94]
### Describe the Bug

You cannot go up a floor using the elevator blocks (supposed to work by jumping).  You can go down a floor using crouch.
One of the mod devs for tech reborn suggested it may be a conflict related to how they "hooked the keybind"

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v1.8.0

### Optifine

No

### Other Mods

Only mods included in Prominence I

**Comment by nvb-uy** [comment]
Can't repro
