### ISSUE TITLE
Spectrum Quests give items that should not be made available to players

### ISSUE THREAD

**Issue by Gronglegrowth** [LunaPixelStudios/Prominence#95]
### Describe the Bug

In the Spectrum questline, there is a quest "What's To Come Next?" which _should be removed_, as well as the quests following it. This quest grants players _Moonstone_, and several other items, which **are not intended to be obtainable** at all in survival in the current release of the mod. By giving players access to these, they are experiencing the mod as was not intended, and are seeing **unfinished and not survival-ready content**.

I come on behalf of the Spectrum discord, where we have had _numerous_ people question what to do with this content, because it is _unfinished_, and it leaves everyone involved confused.

### Operating System

Linux, but it really does not matter in this case.

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.8.0

### Optifine

No

**Comment by Buggy123** [comment]
I don't particularly see the issue with giving the player unfinished/buggy content as a easter egg if they're properly informed as such. I used a glitch in my MC world (not on the Prominence pack) to obtain it, and I thought it was interesting and had fun exploring what the future holds.

That said, the fact that many users are confused and turning to the Spectrum discord for information about these items _is_ a issue. They're probably skipping over the quest text. I would recommend adding a popup or a chat message on quest completion that tells them this content is unfinished.

**Comment by Gronglegrowth** [comment]
Another, and perhaps more serious, issue arising from this, is that by granting players these items, their **progression will be broken** should they remain on the same world when the next release of Spectrum comes out.

All of these items will have an intended method of getting them in said next release, and should the player already have these, they will be left even more confused, as **they will have missed several needed intermediate steps**.

**Comment by nvb-uy** [comment]
The Spectrum questline was a community effort and a decision like this should be made through our Discord's suggestions, people should vote whether they want this or not.

**Comment by nvb-uy** [comment]
Removed in v2.0.0
