### ISSUE TITLE
Problem with Patchouli

### ISSUE THREAD

**Issue by Xavier3554** [LunaPixelStudios/Prominence#96]
Not entirely sure if it's a bug or just my install that decided to be funky... But I'm unable to open any of the in game instruction books as it says that Pachouli isn't installed / missing. 

I went into the mod folder and put the latest version of patchouli I could find, into it but it still doesn't recognize it as being there. Haven't see any sort of mention around the mod not being installed so there's a good likelihood that my install version from forge just messed up and it for some reason isn't in the pack as a whole. Just wondering if anyone had any sort of idea of a potential fix / info if the mod just wasn't added into the pack as a whole

![image](https://github.com/LunaPixelStudios/Prominence/assets/139079176/c7e26f00-67ac-44c3-80ce-539f6ce04a8e)

**Comment by nvb-uy** [comment]
Are you using TLauncher? We do not support pirated launchers
