### ISSUE TITLE
Item dragging/transfer often causes crashes

### ISSUE THREAD

**Issue by Icarus-Creed** [LunaPixelStudios/Prominence#97]
### Describe the Bug

transferring items between containers via shift-click or shift-dragclick often results in a crash with the error reporting that various indices (it's often different ones) were out of bounds for duration 39. Most problematic container is the backpack (of various sizes) but goblin traders (when selecting a trade), grindstones, and crafting benches have all had this problem.

### Reproduction Steps

1. Acquire backpack (preferably iron) and stacks of various items
2. Shift-dragclick transfer items to and from the bag (it doesn't always crash on transfer)
3. Crash.

### Crash Report or Log

https://pastebin.com/vvC9PHMU

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Prominence v1.0.2

### Optifine

No

**Comment by nvb-uy** [comment]
Remove smooth swapping, will be fixed by next update
