### ISSUE TITLE
Essential mod glitching the menu

### ISSUE THREAD

**Issue by olievrr** [LunaPixelStudios/Prominence#98]
### Describe the Bug

Me and my friend wanted to play together so we installed the essential mod. When we loaded in then some menu buttons were missing.

### Reproduction Steps

1. Install prominece I fabric modpack 1.8.0
2. Install and add essential 1.19.2 fabric to the folder
3. Open the game
...

### Screenshots and Videos

![image_2023-07-12_180905398](https://github.com/LunaPixelStudios/Prominence/assets/139368578/924adabb-c37b-457e-ab96-e6f597a6d40c)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.8.0

### Optifine

No

### Other Mods

Essential fabric 1.19.2

**Comment by nvb-uy** [comment]
Not an issue, it's incompatible with our packs.
